// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/push.proto

package violet.gateway.common.proto_gen.push;

public interface PushRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:push.PushRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.im.MessageBody msg_body = 1;</code>
     */
    boolean hasMsgBody();

    /**
     * <code>.im.MessageBody msg_body = 1;</code>
     */
    violet.gateway.common.proto_gen.im.MessageBody getMsgBody();

    /**
     * <code>.im.MessageBody msg_body = 1;</code>
     */
    violet.gateway.common.proto_gen.im.MessageBodyOrBuilder getMsgBodyOrBuilder();

    /**
     * <code>int64 receiver_id = 2;</code>
     */
    long getReceiverId();

    /**
     * <code>int64 badge_count = 3;</code>
     */
    long getBadgeCount();

    /**
     * <code>int64 user_con_index = 4;</code>
     */
    long getUserConIndex();

    /**
     * <code>int64 pre_user_con_index = 5;</code>
     */
    long getPreUserConIndex();

    /**
     * <code>int64 user_cmd_index = 6;</code>
     */
    long getUserCmdIndex();
}
