// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.gateway.common.proto_gen.action;

/**
 * Protobuf type {@code action.MGetFollowCountResponse}
 */
public final class MGetFollowCountResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:action.MGetFollowCountResponse)
        MGetFollowCountResponseOrBuilder {
    // Use MGetFollowCountResponse.newBuilder() to construct.
    private MGetFollowCountResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private MGetFollowCountResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private MGetFollowCountResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            followingCount_ = com.google.protobuf.MapField.newMapField(
                                    FollowingCountDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000001;
                        }
                        com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
                                followingCount__ = input.readMessage(
                                FollowingCountDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        followingCount_.getMutableMap().put(
                                followingCount__.getKey(), followingCount__.getValue());
                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            followerCount_ = com.google.protobuf.MapField.newMapField(
                                    FollowerCountDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000002;
                        }
                        com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
                                followerCount__ = input.readMessage(
                                FollowerCountDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        followerCount_.getMutableMap().put(
                                followerCount__.getKey(), followerCount__.getValue());
                        break;
                    }
                    case 26: {
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            friendCount_ = com.google.protobuf.MapField.newMapField(
                                    FriendCountDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000004;
                        }
                        com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
                                friendCount__ = input.readMessage(
                                FriendCountDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        friendCount_.getMutableMap().put(
                                friendCount__.getKey(), friendCount__.getValue());
                        break;
                    }
                    case 2042: {
                        violet.gateway.common.proto_gen.common.BaseResp.Builder subBuilder = null;
                        if (baseResp_ != null) {
                            subBuilder = baseResp_.toBuilder();
                        }
                        baseResp_ = input.readMessage(violet.gateway.common.proto_gen.common.BaseResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(baseResp_);
                            baseResp_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
        switch (number) {
            case 1:
                return internalGetFollowingCount();
            case 2:
                return internalGetFollowerCount();
            case 3:
                return internalGetFriendCount();
            default:
                throw new RuntimeException(
                        "Invalid map field number: " + number);
        }
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        violet.gateway.common.proto_gen.action.MGetFollowCountResponse.class, violet.gateway.common.proto_gen.action.MGetFollowCountResponse.Builder.class);
    }

    private int bitField0_;
    public static final int FOLLOWING_COUNT_FIELD_NUMBER = 1;

    private static final class FollowingCountDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.Long, java.lang.Long> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.Long, java.lang.Long>newDefaultInstance(
                                violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_FollowingCountEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.INT64,
                                0L,
                                com.google.protobuf.WireFormat.FieldType.INT64,
                                0L);
    }

    private com.google.protobuf.MapField<
            java.lang.Long, java.lang.Long> followingCount_;

    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
    internalGetFollowingCount() {
        if (followingCount_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    FollowingCountDefaultEntryHolder.defaultEntry);
        }
        return followingCount_;
    }

    public int getFollowingCountCount() {
        return internalGetFollowingCount().getMap().size();
    }

    /**
     * <code>map&lt;int64, int64&gt; following_count = 1;</code>
     */

    public boolean containsFollowingCount(
            long key) {

        return internalGetFollowingCount().getMap().containsKey(key);
    }

    /**
     * Use {@link #getFollowingCountMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long> getFollowingCount() {
        return getFollowingCountMap();
    }

    /**
     * <code>map&lt;int64, int64&gt; following_count = 1;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.Long> getFollowingCountMap() {
        return internalGetFollowingCount().getMap();
    }

    /**
     * <code>map&lt;int64, int64&gt; following_count = 1;</code>
     */

    public long getFollowingCountOrDefault(
            long key,
            long defaultValue) {

        java.util.Map<java.lang.Long, java.lang.Long> map =
                internalGetFollowingCount().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;int64, int64&gt; following_count = 1;</code>
     */

    public long getFollowingCountOrThrow(
            long key) {

        java.util.Map<java.lang.Long, java.lang.Long> map =
                internalGetFollowingCount().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    public static final int FOLLOWER_COUNT_FIELD_NUMBER = 2;

    private static final class FollowerCountDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.Long, java.lang.Long> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.Long, java.lang.Long>newDefaultInstance(
                                violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_FollowerCountEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.INT64,
                                0L,
                                com.google.protobuf.WireFormat.FieldType.INT64,
                                0L);
    }

    private com.google.protobuf.MapField<
            java.lang.Long, java.lang.Long> followerCount_;

    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
    internalGetFollowerCount() {
        if (followerCount_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    FollowerCountDefaultEntryHolder.defaultEntry);
        }
        return followerCount_;
    }

    public int getFollowerCountCount() {
        return internalGetFollowerCount().getMap().size();
    }

    /**
     * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
     */

    public boolean containsFollowerCount(
            long key) {

        return internalGetFollowerCount().getMap().containsKey(key);
    }

    /**
     * Use {@link #getFollowerCountMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long> getFollowerCount() {
        return getFollowerCountMap();
    }

    /**
     * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.Long> getFollowerCountMap() {
        return internalGetFollowerCount().getMap();
    }

    /**
     * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
     */

    public long getFollowerCountOrDefault(
            long key,
            long defaultValue) {

        java.util.Map<java.lang.Long, java.lang.Long> map =
                internalGetFollowerCount().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
     */

    public long getFollowerCountOrThrow(
            long key) {

        java.util.Map<java.lang.Long, java.lang.Long> map =
                internalGetFollowerCount().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    public static final int FRIEND_COUNT_FIELD_NUMBER = 3;

    private static final class FriendCountDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.Long, java.lang.Long> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.Long, java.lang.Long>newDefaultInstance(
                                violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_FriendCountEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.INT64,
                                0L,
                                com.google.protobuf.WireFormat.FieldType.INT64,
                                0L);
    }

    private com.google.protobuf.MapField<
            java.lang.Long, java.lang.Long> friendCount_;

    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
    internalGetFriendCount() {
        if (friendCount_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    FriendCountDefaultEntryHolder.defaultEntry);
        }
        return friendCount_;
    }

    public int getFriendCountCount() {
        return internalGetFriendCount().getMap().size();
    }

    /**
     * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
     */

    public boolean containsFriendCount(
            long key) {

        return internalGetFriendCount().getMap().containsKey(key);
    }

    /**
     * Use {@link #getFriendCountMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long> getFriendCount() {
        return getFriendCountMap();
    }

    /**
     * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.Long> getFriendCountMap() {
        return internalGetFriendCount().getMap();
    }

    /**
     * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
     */

    public long getFriendCountOrDefault(
            long key,
            long defaultValue) {

        java.util.Map<java.lang.Long, java.lang.Long> map =
                internalGetFriendCount().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
     */

    public long getFriendCountOrThrow(
            long key) {

        java.util.Map<java.lang.Long, java.lang.Long> map =
                internalGetFriendCount().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    public static final int BASERESP_FIELD_NUMBER = 255;
    private violet.gateway.common.proto_gen.common.BaseResp baseResp_;

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    public boolean hasBaseResp() {
        return baseResp_ != null;
    }

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    public violet.gateway.common.proto_gen.common.BaseResp getBaseResp() {
        return baseResp_ == null ? violet.gateway.common.proto_gen.common.BaseResp.getDefaultInstance() : baseResp_;
    }

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    public violet.gateway.common.proto_gen.common.BaseRespOrBuilder getBaseRespOrBuilder() {
        return getBaseResp();
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        com.google.protobuf.GeneratedMessageV3
                .serializeLongMapTo(
                        output,
                        internalGetFollowingCount(),
                        FollowingCountDefaultEntryHolder.defaultEntry,
                        1);
        com.google.protobuf.GeneratedMessageV3
                .serializeLongMapTo(
                        output,
                        internalGetFollowerCount(),
                        FollowerCountDefaultEntryHolder.defaultEntry,
                        2);
        com.google.protobuf.GeneratedMessageV3
                .serializeLongMapTo(
                        output,
                        internalGetFriendCount(),
                        FriendCountDefaultEntryHolder.defaultEntry,
                        3);
        if (baseResp_ != null) {
            output.writeMessage(255, getBaseResp());
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<java.lang.Long, java.lang.Long> entry
                : internalGetFollowingCount().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
                    followingCount__ = FollowingCountDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, followingCount__);
        }
        for (java.util.Map.Entry<java.lang.Long, java.lang.Long> entry
                : internalGetFollowerCount().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
                    followerCount__ = FollowerCountDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, followerCount__);
        }
        for (java.util.Map.Entry<java.lang.Long, java.lang.Long> entry
                : internalGetFriendCount().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
                    friendCount__ = FriendCountDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, friendCount__);
        }
        if (baseResp_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(255, getBaseResp());
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof violet.gateway.common.proto_gen.action.MGetFollowCountResponse)) {
            return super.equals(obj);
        }
        violet.gateway.common.proto_gen.action.MGetFollowCountResponse other = (violet.gateway.common.proto_gen.action.MGetFollowCountResponse) obj;

        boolean result = true;
        result = result && internalGetFollowingCount().equals(
                other.internalGetFollowingCount());
        result = result && internalGetFollowerCount().equals(
                other.internalGetFollowerCount());
        result = result && internalGetFriendCount().equals(
                other.internalGetFriendCount());
        result = result && (hasBaseResp() == other.hasBaseResp());
        if (hasBaseResp()) {
            result = result && getBaseResp()
                    .equals(other.getBaseResp());
        }
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (!internalGetFollowingCount().getMap().isEmpty()) {
            hash = (37 * hash) + FOLLOWING_COUNT_FIELD_NUMBER;
            hash = (53 * hash) + internalGetFollowingCount().hashCode();
        }
        if (!internalGetFollowerCount().getMap().isEmpty()) {
            hash = (37 * hash) + FOLLOWER_COUNT_FIELD_NUMBER;
            hash = (53 * hash) + internalGetFollowerCount().hashCode();
        }
        if (!internalGetFriendCount().getMap().isEmpty()) {
            hash = (37 * hash) + FRIEND_COUNT_FIELD_NUMBER;
            hash = (53 * hash) + internalGetFriendCount().hashCode();
        }
        if (hasBaseResp()) {
            hash = (37 * hash) + BASERESP_FIELD_NUMBER;
            hash = (53 * hash) + getBaseResp().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(violet.gateway.common.proto_gen.action.MGetFollowCountResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code action.MGetFollowCountResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:action.MGetFollowCountResponse)
            violet.gateway.common.proto_gen.action.MGetFollowCountResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetFollowingCount();
                case 2:
                    return internalGetFollowerCount();
                case 3:
                    return internalGetFriendCount();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetMutableFollowingCount();
                case 2:
                    return internalGetMutableFollowerCount();
                case 3:
                    return internalGetMutableFriendCount();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            violet.gateway.common.proto_gen.action.MGetFollowCountResponse.class, violet.gateway.common.proto_gen.action.MGetFollowCountResponse.Builder.class);
        }

        // Construct using violet.gateway.common.proto_gen.action.MGetFollowCountResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            internalGetMutableFollowingCount().clear();
            internalGetMutableFollowerCount().clear();
            internalGetMutableFriendCount().clear();
            if (baseRespBuilder_ == null) {
                baseResp_ = null;
            } else {
                baseResp_ = null;
                baseRespBuilder_ = null;
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return violet.gateway.common.proto_gen.action.Action.internal_static_action_MGetFollowCountResponse_descriptor;
        }

        public violet.gateway.common.proto_gen.action.MGetFollowCountResponse getDefaultInstanceForType() {
            return violet.gateway.common.proto_gen.action.MGetFollowCountResponse.getDefaultInstance();
        }

        public violet.gateway.common.proto_gen.action.MGetFollowCountResponse build() {
            violet.gateway.common.proto_gen.action.MGetFollowCountResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public violet.gateway.common.proto_gen.action.MGetFollowCountResponse buildPartial() {
            violet.gateway.common.proto_gen.action.MGetFollowCountResponse result = new violet.gateway.common.proto_gen.action.MGetFollowCountResponse(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.followingCount_ = internalGetFollowingCount();
            result.followingCount_.makeImmutable();
            result.followerCount_ = internalGetFollowerCount();
            result.followerCount_.makeImmutable();
            result.friendCount_ = internalGetFriendCount();
            result.friendCount_.makeImmutable();
            if (baseRespBuilder_ == null) {
                result.baseResp_ = baseResp_;
            } else {
                result.baseResp_ = baseRespBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof violet.gateway.common.proto_gen.action.MGetFollowCountResponse) {
                return mergeFrom((violet.gateway.common.proto_gen.action.MGetFollowCountResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(violet.gateway.common.proto_gen.action.MGetFollowCountResponse other) {
            if (other == violet.gateway.common.proto_gen.action.MGetFollowCountResponse.getDefaultInstance())
                return this;
            internalGetMutableFollowingCount().mergeFrom(
                    other.internalGetFollowingCount());
            internalGetMutableFollowerCount().mergeFrom(
                    other.internalGetFollowerCount());
            internalGetMutableFriendCount().mergeFrom(
                    other.internalGetFriendCount());
            if (other.hasBaseResp()) {
                mergeBaseResp(other.getBaseResp());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            violet.gateway.common.proto_gen.action.MGetFollowCountResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (violet.gateway.common.proto_gen.action.MGetFollowCountResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private com.google.protobuf.MapField<
                java.lang.Long, java.lang.Long> followingCount_;

        private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetFollowingCount() {
            if (followingCount_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        FollowingCountDefaultEntryHolder.defaultEntry);
            }
            return followingCount_;
        }

        private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetMutableFollowingCount() {
            onChanged();
            ;
            if (followingCount_ == null) {
                followingCount_ = com.google.protobuf.MapField.newMapField(
                        FollowingCountDefaultEntryHolder.defaultEntry);
            }
            if (!followingCount_.isMutable()) {
                followingCount_ = followingCount_.copy();
            }
            return followingCount_;
        }

        public int getFollowingCountCount() {
            return internalGetFollowingCount().getMap().size();
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */

        public boolean containsFollowingCount(
                long key) {

            return internalGetFollowingCount().getMap().containsKey(key);
        }

        /**
         * Use {@link #getFollowingCountMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Long, java.lang.Long> getFollowingCount() {
            return getFollowingCountMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */

        public java.util.Map<java.lang.Long, java.lang.Long> getFollowingCountMap() {
            return internalGetFollowingCount().getMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */

        public long getFollowingCountOrDefault(
                long key,
                long defaultValue) {

            java.util.Map<java.lang.Long, java.lang.Long> map =
                    internalGetFollowingCount().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */

        public long getFollowingCountOrThrow(
                long key) {

            java.util.Map<java.lang.Long, java.lang.Long> map =
                    internalGetFollowingCount().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearFollowingCount() {
            internalGetMutableFollowingCount().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */

        public Builder removeFollowingCount(
                long key) {

            internalGetMutableFollowingCount().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Long, java.lang.Long>
        getMutableFollowingCount() {
            return internalGetMutableFollowingCount().getMutableMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */
        public Builder putFollowingCount(
                long key,
                long value) {


            internalGetMutableFollowingCount().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;int64, int64&gt; following_count = 1;</code>
         */

        public Builder putAllFollowingCount(
                java.util.Map<java.lang.Long, java.lang.Long> values) {
            internalGetMutableFollowingCount().getMutableMap()
                    .putAll(values);
            return this;
        }

        private com.google.protobuf.MapField<
                java.lang.Long, java.lang.Long> followerCount_;

        private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetFollowerCount() {
            if (followerCount_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        FollowerCountDefaultEntryHolder.defaultEntry);
            }
            return followerCount_;
        }

        private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetMutableFollowerCount() {
            onChanged();
            ;
            if (followerCount_ == null) {
                followerCount_ = com.google.protobuf.MapField.newMapField(
                        FollowerCountDefaultEntryHolder.defaultEntry);
            }
            if (!followerCount_.isMutable()) {
                followerCount_ = followerCount_.copy();
            }
            return followerCount_;
        }

        public int getFollowerCountCount() {
            return internalGetFollowerCount().getMap().size();
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */

        public boolean containsFollowerCount(
                long key) {

            return internalGetFollowerCount().getMap().containsKey(key);
        }

        /**
         * Use {@link #getFollowerCountMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Long, java.lang.Long> getFollowerCount() {
            return getFollowerCountMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */

        public java.util.Map<java.lang.Long, java.lang.Long> getFollowerCountMap() {
            return internalGetFollowerCount().getMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */

        public long getFollowerCountOrDefault(
                long key,
                long defaultValue) {

            java.util.Map<java.lang.Long, java.lang.Long> map =
                    internalGetFollowerCount().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */

        public long getFollowerCountOrThrow(
                long key) {

            java.util.Map<java.lang.Long, java.lang.Long> map =
                    internalGetFollowerCount().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearFollowerCount() {
            internalGetMutableFollowerCount().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */

        public Builder removeFollowerCount(
                long key) {

            internalGetMutableFollowerCount().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Long, java.lang.Long>
        getMutableFollowerCount() {
            return internalGetMutableFollowerCount().getMutableMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */
        public Builder putFollowerCount(
                long key,
                long value) {


            internalGetMutableFollowerCount().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;int64, int64&gt; follower_count = 2;</code>
         */

        public Builder putAllFollowerCount(
                java.util.Map<java.lang.Long, java.lang.Long> values) {
            internalGetMutableFollowerCount().getMutableMap()
                    .putAll(values);
            return this;
        }

        private com.google.protobuf.MapField<
                java.lang.Long, java.lang.Long> friendCount_;

        private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetFriendCount() {
            if (friendCount_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        FriendCountDefaultEntryHolder.defaultEntry);
            }
            return friendCount_;
        }

        private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
        internalGetMutableFriendCount() {
            onChanged();
            ;
            if (friendCount_ == null) {
                friendCount_ = com.google.protobuf.MapField.newMapField(
                        FriendCountDefaultEntryHolder.defaultEntry);
            }
            if (!friendCount_.isMutable()) {
                friendCount_ = friendCount_.copy();
            }
            return friendCount_;
        }

        public int getFriendCountCount() {
            return internalGetFriendCount().getMap().size();
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */

        public boolean containsFriendCount(
                long key) {

            return internalGetFriendCount().getMap().containsKey(key);
        }

        /**
         * Use {@link #getFriendCountMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Long, java.lang.Long> getFriendCount() {
            return getFriendCountMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */

        public java.util.Map<java.lang.Long, java.lang.Long> getFriendCountMap() {
            return internalGetFriendCount().getMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */

        public long getFriendCountOrDefault(
                long key,
                long defaultValue) {

            java.util.Map<java.lang.Long, java.lang.Long> map =
                    internalGetFriendCount().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */

        public long getFriendCountOrThrow(
                long key) {

            java.util.Map<java.lang.Long, java.lang.Long> map =
                    internalGetFriendCount().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearFriendCount() {
            internalGetMutableFriendCount().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */

        public Builder removeFriendCount(
                long key) {

            internalGetMutableFriendCount().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Long, java.lang.Long>
        getMutableFriendCount() {
            return internalGetMutableFriendCount().getMutableMap();
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */
        public Builder putFriendCount(
                long key,
                long value) {


            internalGetMutableFriendCount().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;int64, int64&gt; friend_count = 3;</code>
         */

        public Builder putAllFriendCount(
                java.util.Map<java.lang.Long, java.lang.Long> values) {
            internalGetMutableFriendCount().getMutableMap()
                    .putAll(values);
            return this;
        }

        private violet.gateway.common.proto_gen.common.BaseResp baseResp_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.common.BaseResp, violet.gateway.common.proto_gen.common.BaseResp.Builder, violet.gateway.common.proto_gen.common.BaseRespOrBuilder> baseRespBuilder_;

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public boolean hasBaseResp() {
            return baseRespBuilder_ != null || baseResp_ != null;
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public violet.gateway.common.proto_gen.common.BaseResp getBaseResp() {
            if (baseRespBuilder_ == null) {
                return baseResp_ == null ? violet.gateway.common.proto_gen.common.BaseResp.getDefaultInstance() : baseResp_;
            } else {
                return baseRespBuilder_.getMessage();
            }
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public Builder setBaseResp(violet.gateway.common.proto_gen.common.BaseResp value) {
            if (baseRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                baseResp_ = value;
                onChanged();
            } else {
                baseRespBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public Builder setBaseResp(
                violet.gateway.common.proto_gen.common.BaseResp.Builder builderForValue) {
            if (baseRespBuilder_ == null) {
                baseResp_ = builderForValue.build();
                onChanged();
            } else {
                baseRespBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public Builder mergeBaseResp(violet.gateway.common.proto_gen.common.BaseResp value) {
            if (baseRespBuilder_ == null) {
                if (baseResp_ != null) {
                    baseResp_ =
                            violet.gateway.common.proto_gen.common.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
                } else {
                    baseResp_ = value;
                }
                onChanged();
            } else {
                baseRespBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public Builder clearBaseResp() {
            if (baseRespBuilder_ == null) {
                baseResp_ = null;
                onChanged();
            } else {
                baseResp_ = null;
                baseRespBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public violet.gateway.common.proto_gen.common.BaseResp.Builder getBaseRespBuilder() {

            onChanged();
            return getBaseRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        public violet.gateway.common.proto_gen.common.BaseRespOrBuilder getBaseRespOrBuilder() {
            if (baseRespBuilder_ != null) {
                return baseRespBuilder_.getMessageOrBuilder();
            } else {
                return baseResp_ == null ?
                        violet.gateway.common.proto_gen.common.BaseResp.getDefaultInstance() : baseResp_;
            }
        }

        /**
         * <code>.common.BaseResp baseResp = 255;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.common.BaseResp, violet.gateway.common.proto_gen.common.BaseResp.Builder, violet.gateway.common.proto_gen.common.BaseRespOrBuilder>
        getBaseRespFieldBuilder() {
            if (baseRespBuilder_ == null) {
                baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        violet.gateway.common.proto_gen.common.BaseResp, violet.gateway.common.proto_gen.common.BaseResp.Builder, violet.gateway.common.proto_gen.common.BaseRespOrBuilder>(
                        getBaseResp(),
                        getParentForChildren(),
                        isClean());
                baseResp_ = null;
            }
            return baseRespBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:action.MGetFollowCountResponse)
    }

    // @@protoc_insertion_point(class_scope:action.MGetFollowCountResponse)
    private static final violet.gateway.common.proto_gen.action.MGetFollowCountResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.action.MGetFollowCountResponse();
    }

    public static violet.gateway.common.proto_gen.action.MGetFollowCountResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MGetFollowCountResponse>
            PARSER = new com.google.protobuf.AbstractParser<MGetFollowCountResponse>() {
        public MGetFollowCountResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new MGetFollowCountResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<MGetFollowCountResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MGetFollowCountResponse> getParserForType() {
        return PARSER;
    }

    public violet.gateway.common.proto_gen.action.MGetFollowCountResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

