// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.gateway.common.proto_gen.action;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:action.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   */
  long getUserId();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
