// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

public interface AddConversationMembersResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:im.AddConversationMembersResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    boolean hasBaseResp();

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    violet.gateway.common.proto_gen.common.BaseResp getBaseResp();

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    violet.gateway.common.proto_gen.common.BaseRespOrBuilder getBaseRespOrBuilder();
}
