// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf type {@code im.AddConversationMembersRequest}
 */
public  final class AddConversationMembersRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.AddConversationMembersRequest)
    AddConversationMembersRequestOrBuilder {
  // Use AddConversationMembersRequest.newBuilder() to construct.
  private AddConversationMembersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddConversationMembersRequest() {
    conShortId_ = 0L;
    conId_ = "";
    members_ = java.util.Collections.emptyList();
    operator_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AddConversationMembersRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            conShortId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            conId_ = s;
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              members_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            members_.add(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              members_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              members_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {

            operator_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        members_ = java.util.Collections.unmodifiableList(members_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return violet.gateway.common.proto_gen.im.Im.internal_static_im_AddConversationMembersRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return violet.gateway.common.proto_gen.im.Im.internal_static_im_AddConversationMembersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            violet.gateway.common.proto_gen.im.AddConversationMembersRequest.class, violet.gateway.common.proto_gen.im.AddConversationMembersRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CON_SHORT_ID_FIELD_NUMBER = 1;
  private long conShortId_;
  /**
   * <code>int64 con_short_id = 1;</code>
   */
  public long getConShortId() {
    return conShortId_;
  }

  public static final int CON_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object conId_;
  /**
   * <code>string con_id = 2;</code>
   */
  public java.lang.String getConId() {
    java.lang.Object ref = conId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conId_ = s;
      return s;
    }
  }
  /**
   * <code>string con_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConIdBytes() {
    java.lang.Object ref = conId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMBERS_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Long> members_;
  /**
   * <code>repeated int64 members = 3;</code>
   */
  public java.util.List<java.lang.Long>
      getMembersList() {
    return members_;
  }
  /**
   * <code>repeated int64 members = 3;</code>
   */
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated int64 members = 3;</code>
   */
  public long getMembers(int index) {
    return members_.get(index);
  }
  private int membersMemoizedSerializedSize = -1;

  public static final int OPERATOR_FIELD_NUMBER = 4;
  private long operator_;
  /**
   * <code>int64 operator = 4;</code>
   */
  public long getOperator() {
    return operator_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (conShortId_ != 0L) {
      output.writeInt64(1, conShortId_);
    }
    if (!getConIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conId_);
    }
    if (getMembersList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(membersMemoizedSerializedSize);
    }
    for (int i = 0; i < members_.size(); i++) {
      output.writeInt64NoTag(members_.get(i));
    }
    if (operator_ != 0L) {
      output.writeInt64(4, operator_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (conShortId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, conShortId_);
    }
    if (!getConIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < members_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(members_.get(i));
      }
      size += dataSize;
      if (!getMembersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      membersMemoizedSerializedSize = dataSize;
    }
    if (operator_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, operator_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof violet.gateway.common.proto_gen.im.AddConversationMembersRequest)) {
      return super.equals(obj);
    }
    violet.gateway.common.proto_gen.im.AddConversationMembersRequest other = (violet.gateway.common.proto_gen.im.AddConversationMembersRequest) obj;

    boolean result = true;
    result = result && (getConShortId()
        == other.getConShortId());
    result = result && getConId()
        .equals(other.getConId());
    result = result && getMembersList()
        .equals(other.getMembersList());
    result = result && (getOperator()
        == other.getOperator());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CON_SHORT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getConShortId());
    hash = (37 * hash) + CON_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConId().hashCode();
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOperator());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(violet.gateway.common.proto_gen.im.AddConversationMembersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.AddConversationMembersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.AddConversationMembersRequest)
      violet.gateway.common.proto_gen.im.AddConversationMembersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_AddConversationMembersRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_AddConversationMembersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              violet.gateway.common.proto_gen.im.AddConversationMembersRequest.class, violet.gateway.common.proto_gen.im.AddConversationMembersRequest.Builder.class);
    }

    // Construct using violet.gateway.common.proto_gen.im.AddConversationMembersRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      conShortId_ = 0L;

      conId_ = "";

      members_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      operator_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_AddConversationMembersRequest_descriptor;
    }

    public violet.gateway.common.proto_gen.im.AddConversationMembersRequest getDefaultInstanceForType() {
      return violet.gateway.common.proto_gen.im.AddConversationMembersRequest.getDefaultInstance();
    }

    public violet.gateway.common.proto_gen.im.AddConversationMembersRequest build() {
      violet.gateway.common.proto_gen.im.AddConversationMembersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public violet.gateway.common.proto_gen.im.AddConversationMembersRequest buildPartial() {
      violet.gateway.common.proto_gen.im.AddConversationMembersRequest result = new violet.gateway.common.proto_gen.im.AddConversationMembersRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.conShortId_ = conShortId_;
      result.conId_ = conId_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        members_ = java.util.Collections.unmodifiableList(members_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.members_ = members_;
      result.operator_ = operator_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof violet.gateway.common.proto_gen.im.AddConversationMembersRequest) {
        return mergeFrom((violet.gateway.common.proto_gen.im.AddConversationMembersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(violet.gateway.common.proto_gen.im.AddConversationMembersRequest other) {
      if (other == violet.gateway.common.proto_gen.im.AddConversationMembersRequest.getDefaultInstance()) return this;
      if (other.getConShortId() != 0L) {
        setConShortId(other.getConShortId());
      }
      if (!other.getConId().isEmpty()) {
        conId_ = other.conId_;
        onChanged();
      }
      if (!other.members_.isEmpty()) {
        if (members_.isEmpty()) {
          members_ = other.members_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureMembersIsMutable();
          members_.addAll(other.members_);
        }
        onChanged();
      }
      if (other.getOperator() != 0L) {
        setOperator(other.getOperator());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      violet.gateway.common.proto_gen.im.AddConversationMembersRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (violet.gateway.common.proto_gen.im.AddConversationMembersRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long conShortId_ ;
    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public long getConShortId() {
      return conShortId_;
    }
    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public Builder setConShortId(long value) {
      
      conShortId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public Builder clearConShortId() {
      
      conShortId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object conId_ = "";
    /**
     * <code>string con_id = 2;</code>
     */
    public java.lang.String getConId() {
      java.lang.Object ref = conId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string con_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConIdBytes() {
      java.lang.Object ref = conId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string con_id = 2;</code>
     */
    public Builder setConId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string con_id = 2;</code>
     */
    public Builder clearConId() {
      
      conId_ = getDefaultInstance().getConId();
      onChanged();
      return this;
    }
    /**
     * <code>string con_id = 2;</code>
     */
    public Builder setConIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> members_ = java.util.Collections.emptyList();
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        members_ = new java.util.ArrayList<java.lang.Long>(members_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getMembersList() {
      return java.util.Collections.unmodifiableList(members_);
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public long getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public Builder setMembers(
        int index, long value) {
      ensureMembersIsMutable();
      members_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public Builder addMembers(long value) {
      ensureMembersIsMutable();
      members_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public Builder addAllMembers(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureMembersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, members_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 members = 3;</code>
     */
    public Builder clearMembers() {
      members_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private long operator_ ;
    /**
     * <code>int64 operator = 4;</code>
     */
    public long getOperator() {
      return operator_;
    }
    /**
     * <code>int64 operator = 4;</code>
     */
    public Builder setOperator(long value) {
      
      operator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 operator = 4;</code>
     */
    public Builder clearOperator() {
      
      operator_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:im.AddConversationMembersRequest)
  }

  // @@protoc_insertion_point(class_scope:im.AddConversationMembersRequest)
  private static final violet.gateway.common.proto_gen.im.AddConversationMembersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.im.AddConversationMembersRequest();
  }

  public static violet.gateway.common.proto_gen.im.AddConversationMembersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddConversationMembersRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddConversationMembersRequest>() {
    public AddConversationMembersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddConversationMembersRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddConversationMembersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddConversationMembersRequest> getParserForType() {
    return PARSER;
  }

  public violet.gateway.common.proto_gen.im.AddConversationMembersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

