// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf enum {@code im.CommandType}
 */
public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CommandType_Not_Use = 0;</code>
     */
    CommandType_Not_Use(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CommandType_Not_Use = 0;</code>
     */
    public static final int CommandType_Not_Use_VALUE = 0;


    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
        return forNumber(value);
    }

    public static CommandType forNumber(int value) {
        switch (value) {
            case 0:
                return CommandType_Not_Use;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            CommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
                public CommandType findValueByNumber(int number) {
                    return CommandType.forNumber(number);
                }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
        return violet.gateway.common.proto_gen.im.Im.getDescriptor().getEnumTypes().get(2);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.CommandType)
}

