// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf type {@code im.ConversationMessage}
 */
public final class ConversationMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:im.ConversationMessage)
        ConversationMessageOrBuilder {
    // Use ConversationMessage.newBuilder() to construct.
    private ConversationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ConversationMessage() {
        msgBodies_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ConversationMessage(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        violet.gateway.common.proto_gen.im.ConversationInfo.Builder subBuilder = null;
                        if (conInfo_ != null) {
                            subBuilder = conInfo_.toBuilder();
                        }
                        conInfo_ = input.readMessage(violet.gateway.common.proto_gen.im.ConversationInfo.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(conInfo_);
                            conInfo_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            msgBodies_ = new java.util.ArrayList<violet.gateway.common.proto_gen.im.MessageBody>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        msgBodies_.add(
                                input.readMessage(violet.gateway.common.proto_gen.im.MessageBody.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                msgBodies_ = java.util.Collections.unmodifiableList(msgBodies_);
            }
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        violet.gateway.common.proto_gen.im.ConversationMessage.class, violet.gateway.common.proto_gen.im.ConversationMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CON_INFO_FIELD_NUMBER = 1;
    private violet.gateway.common.proto_gen.im.ConversationInfo conInfo_;

    /**
     * <code>.im.ConversationInfo con_info = 1;</code>
     */
    public boolean hasConInfo() {
        return conInfo_ != null;
    }

    /**
     * <code>.im.ConversationInfo con_info = 1;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationInfo getConInfo() {
        return conInfo_ == null ? violet.gateway.common.proto_gen.im.ConversationInfo.getDefaultInstance() : conInfo_;
    }

    /**
     * <code>.im.ConversationInfo con_info = 1;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationInfoOrBuilder getConInfoOrBuilder() {
        return getConInfo();
    }

    public static final int MSG_BODIES_FIELD_NUMBER = 2;
    private java.util.List<violet.gateway.common.proto_gen.im.MessageBody> msgBodies_;

    /**
     * <code>repeated .im.MessageBody msg_bodies = 2;</code>
     */
    public java.util.List<violet.gateway.common.proto_gen.im.MessageBody> getMsgBodiesList() {
        return msgBodies_;
    }

    /**
     * <code>repeated .im.MessageBody msg_bodies = 2;</code>
     */
    public java.util.List<? extends violet.gateway.common.proto_gen.im.MessageBodyOrBuilder>
    getMsgBodiesOrBuilderList() {
        return msgBodies_;
    }

    /**
     * <code>repeated .im.MessageBody msg_bodies = 2;</code>
     */
    public int getMsgBodiesCount() {
        return msgBodies_.size();
    }

    /**
     * <code>repeated .im.MessageBody msg_bodies = 2;</code>
     */
    public violet.gateway.common.proto_gen.im.MessageBody getMsgBodies(int index) {
        return msgBodies_.get(index);
    }

    /**
     * <code>repeated .im.MessageBody msg_bodies = 2;</code>
     */
    public violet.gateway.common.proto_gen.im.MessageBodyOrBuilder getMsgBodiesOrBuilder(
            int index) {
        return msgBodies_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (conInfo_ != null) {
            output.writeMessage(1, getConInfo());
        }
        for (int i = 0; i < msgBodies_.size(); i++) {
            output.writeMessage(2, msgBodies_.get(i));
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (conInfo_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getConInfo());
        }
        for (int i = 0; i < msgBodies_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, msgBodies_.get(i));
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof violet.gateway.common.proto_gen.im.ConversationMessage)) {
            return super.equals(obj);
        }
        violet.gateway.common.proto_gen.im.ConversationMessage other = (violet.gateway.common.proto_gen.im.ConversationMessage) obj;

        boolean result = true;
        result = result && (hasConInfo() == other.hasConInfo());
        if (hasConInfo()) {
            result = result && getConInfo()
                    .equals(other.getConInfo());
        }
        result = result && getMsgBodiesList()
                .equals(other.getMsgBodiesList());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasConInfo()) {
            hash = (37 * hash) + CON_INFO_FIELD_NUMBER;
            hash = (53 * hash) + getConInfo().hashCode();
        }
        if (getMsgBodiesCount() > 0) {
            hash = (37 * hash) + MSG_BODIES_FIELD_NUMBER;
            hash = (53 * hash) + getMsgBodiesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(violet.gateway.common.proto_gen.im.ConversationMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code im.ConversationMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:im.ConversationMessage)
            violet.gateway.common.proto_gen.im.ConversationMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            violet.gateway.common.proto_gen.im.ConversationMessage.class, violet.gateway.common.proto_gen.im.ConversationMessage.Builder.class);
        }

        // Construct using violet.gateway.common.proto_gen.im.ConversationMessage.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getMsgBodiesFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (conInfoBuilder_ == null) {
                conInfo_ = null;
            } else {
                conInfo_ = null;
                conInfoBuilder_ = null;
            }
            if (msgBodiesBuilder_ == null) {
                msgBodies_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
            } else {
                msgBodiesBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationMessage_descriptor;
        }

        public violet.gateway.common.proto_gen.im.ConversationMessage getDefaultInstanceForType() {
            return violet.gateway.common.proto_gen.im.ConversationMessage.getDefaultInstance();
        }

        public violet.gateway.common.proto_gen.im.ConversationMessage build() {
            violet.gateway.common.proto_gen.im.ConversationMessage result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public violet.gateway.common.proto_gen.im.ConversationMessage buildPartial() {
            violet.gateway.common.proto_gen.im.ConversationMessage result = new violet.gateway.common.proto_gen.im.ConversationMessage(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (conInfoBuilder_ == null) {
                result.conInfo_ = conInfo_;
            } else {
                result.conInfo_ = conInfoBuilder_.build();
            }
            if (msgBodiesBuilder_ == null) {
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    msgBodies_ = java.util.Collections.unmodifiableList(msgBodies_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.msgBodies_ = msgBodies_;
            } else {
                result.msgBodies_ = msgBodiesBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof violet.gateway.common.proto_gen.im.ConversationMessage) {
                return mergeFrom((violet.gateway.common.proto_gen.im.ConversationMessage) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(violet.gateway.common.proto_gen.im.ConversationMessage other) {
            if (other == violet.gateway.common.proto_gen.im.ConversationMessage.getDefaultInstance()) return this;
            if (other.hasConInfo()) {
                mergeConInfo(other.getConInfo());
            }
            if (msgBodiesBuilder_ == null) {
                if (!other.msgBodies_.isEmpty()) {
                    if (msgBodies_.isEmpty()) {
                        msgBodies_ = other.msgBodies_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureMsgBodiesIsMutable();
                        msgBodies_.addAll(other.msgBodies_);
                    }
                    onChanged();
                }
            } else {
                if (!other.msgBodies_.isEmpty()) {
                    if (msgBodiesBuilder_.isEmpty()) {
                        msgBodiesBuilder_.dispose();
                        msgBodiesBuilder_ = null;
                        msgBodies_ = other.msgBodies_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        msgBodiesBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getMsgBodiesFieldBuilder() : null;
                    } else {
                        msgBodiesBuilder_.addAllMessages(other.msgBodies_);
                    }
                }
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            violet.gateway.common.proto_gen.im.ConversationMessage parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (violet.gateway.common.proto_gen.im.ConversationMessage) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private violet.gateway.common.proto_gen.im.ConversationInfo conInfo_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationInfo, violet.gateway.common.proto_gen.im.ConversationInfo.Builder, violet.gateway.common.proto_gen.im.ConversationInfoOrBuilder> conInfoBuilder_;

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public boolean hasConInfo() {
            return conInfoBuilder_ != null || conInfo_ != null;
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationInfo getConInfo() {
            if (conInfoBuilder_ == null) {
                return conInfo_ == null ? violet.gateway.common.proto_gen.im.ConversationInfo.getDefaultInstance() : conInfo_;
            } else {
                return conInfoBuilder_.getMessage();
            }
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public Builder setConInfo(violet.gateway.common.proto_gen.im.ConversationInfo value) {
            if (conInfoBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                conInfo_ = value;
                onChanged();
            } else {
                conInfoBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public Builder setConInfo(
                violet.gateway.common.proto_gen.im.ConversationInfo.Builder builderForValue) {
            if (conInfoBuilder_ == null) {
                conInfo_ = builderForValue.build();
                onChanged();
            } else {
                conInfoBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public Builder mergeConInfo(violet.gateway.common.proto_gen.im.ConversationInfo value) {
            if (conInfoBuilder_ == null) {
                if (conInfo_ != null) {
                    conInfo_ =
                            violet.gateway.common.proto_gen.im.ConversationInfo.newBuilder(conInfo_).mergeFrom(value).buildPartial();
                } else {
                    conInfo_ = value;
                }
                onChanged();
            } else {
                conInfoBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public Builder clearConInfo() {
            if (conInfoBuilder_ == null) {
                conInfo_ = null;
                onChanged();
            } else {
                conInfo_ = null;
                conInfoBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationInfo.Builder getConInfoBuilder() {

            onChanged();
            return getConInfoFieldBuilder().getBuilder();
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationInfoOrBuilder getConInfoOrBuilder() {
            if (conInfoBuilder_ != null) {
                return conInfoBuilder_.getMessageOrBuilder();
            } else {
                return conInfo_ == null ?
                        violet.gateway.common.proto_gen.im.ConversationInfo.getDefaultInstance() : conInfo_;
            }
        }

        /**
         * <code>.im.ConversationInfo con_info = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationInfo, violet.gateway.common.proto_gen.im.ConversationInfo.Builder, violet.gateway.common.proto_gen.im.ConversationInfoOrBuilder>
        getConInfoFieldBuilder() {
            if (conInfoBuilder_ == null) {
                conInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        violet.gateway.common.proto_gen.im.ConversationInfo, violet.gateway.common.proto_gen.im.ConversationInfo.Builder, violet.gateway.common.proto_gen.im.ConversationInfoOrBuilder>(
                        getConInfo(),
                        getParentForChildren(),
                        isClean());
                conInfo_ = null;
            }
            return conInfoBuilder_;
        }

        private java.util.List<violet.gateway.common.proto_gen.im.MessageBody> msgBodies_ =
                java.util.Collections.emptyList();

        private void ensureMsgBodiesIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                msgBodies_ = new java.util.ArrayList<violet.gateway.common.proto_gen.im.MessageBody>(msgBodies_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                violet.gateway.common.proto_gen.im.MessageBody, violet.gateway.common.proto_gen.im.MessageBody.Builder, violet.gateway.common.proto_gen.im.MessageBodyOrBuilder> msgBodiesBuilder_;

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public java.util.List<violet.gateway.common.proto_gen.im.MessageBody> getMsgBodiesList() {
            if (msgBodiesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(msgBodies_);
            } else {
                return msgBodiesBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public int getMsgBodiesCount() {
            if (msgBodiesBuilder_ == null) {
                return msgBodies_.size();
            } else {
                return msgBodiesBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public violet.gateway.common.proto_gen.im.MessageBody getMsgBodies(int index) {
            if (msgBodiesBuilder_ == null) {
                return msgBodies_.get(index);
            } else {
                return msgBodiesBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder setMsgBodies(
                int index, violet.gateway.common.proto_gen.im.MessageBody value) {
            if (msgBodiesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureMsgBodiesIsMutable();
                msgBodies_.set(index, value);
                onChanged();
            } else {
                msgBodiesBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder setMsgBodies(
                int index, violet.gateway.common.proto_gen.im.MessageBody.Builder builderForValue) {
            if (msgBodiesBuilder_ == null) {
                ensureMsgBodiesIsMutable();
                msgBodies_.set(index, builderForValue.build());
                onChanged();
            } else {
                msgBodiesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder addMsgBodies(violet.gateway.common.proto_gen.im.MessageBody value) {
            if (msgBodiesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureMsgBodiesIsMutable();
                msgBodies_.add(value);
                onChanged();
            } else {
                msgBodiesBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder addMsgBodies(
                int index, violet.gateway.common.proto_gen.im.MessageBody value) {
            if (msgBodiesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureMsgBodiesIsMutable();
                msgBodies_.add(index, value);
                onChanged();
            } else {
                msgBodiesBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder addMsgBodies(
                violet.gateway.common.proto_gen.im.MessageBody.Builder builderForValue) {
            if (msgBodiesBuilder_ == null) {
                ensureMsgBodiesIsMutable();
                msgBodies_.add(builderForValue.build());
                onChanged();
            } else {
                msgBodiesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder addMsgBodies(
                int index, violet.gateway.common.proto_gen.im.MessageBody.Builder builderForValue) {
            if (msgBodiesBuilder_ == null) {
                ensureMsgBodiesIsMutable();
                msgBodies_.add(index, builderForValue.build());
                onChanged();
            } else {
                msgBodiesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder addAllMsgBodies(
                java.lang.Iterable<? extends violet.gateway.common.proto_gen.im.MessageBody> values) {
            if (msgBodiesBuilder_ == null) {
                ensureMsgBodiesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, msgBodies_);
                onChanged();
            } else {
                msgBodiesBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder clearMsgBodies() {
            if (msgBodiesBuilder_ == null) {
                msgBodies_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                msgBodiesBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public Builder removeMsgBodies(int index) {
            if (msgBodiesBuilder_ == null) {
                ensureMsgBodiesIsMutable();
                msgBodies_.remove(index);
                onChanged();
            } else {
                msgBodiesBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public violet.gateway.common.proto_gen.im.MessageBody.Builder getMsgBodiesBuilder(
                int index) {
            return getMsgBodiesFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public violet.gateway.common.proto_gen.im.MessageBodyOrBuilder getMsgBodiesOrBuilder(
                int index) {
            if (msgBodiesBuilder_ == null) {
                return msgBodies_.get(index);
            } else {
                return msgBodiesBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public java.util.List<? extends violet.gateway.common.proto_gen.im.MessageBodyOrBuilder>
        getMsgBodiesOrBuilderList() {
            if (msgBodiesBuilder_ != null) {
                return msgBodiesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(msgBodies_);
            }
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public violet.gateway.common.proto_gen.im.MessageBody.Builder addMsgBodiesBuilder() {
            return getMsgBodiesFieldBuilder().addBuilder(
                    violet.gateway.common.proto_gen.im.MessageBody.getDefaultInstance());
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public violet.gateway.common.proto_gen.im.MessageBody.Builder addMsgBodiesBuilder(
                int index) {
            return getMsgBodiesFieldBuilder().addBuilder(
                    index, violet.gateway.common.proto_gen.im.MessageBody.getDefaultInstance());
        }

        /**
         * <code>repeated .im.MessageBody msg_bodies = 2;</code>
         */
        public java.util.List<violet.gateway.common.proto_gen.im.MessageBody.Builder>
        getMsgBodiesBuilderList() {
            return getMsgBodiesFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                violet.gateway.common.proto_gen.im.MessageBody, violet.gateway.common.proto_gen.im.MessageBody.Builder, violet.gateway.common.proto_gen.im.MessageBodyOrBuilder>
        getMsgBodiesFieldBuilder() {
            if (msgBodiesBuilder_ == null) {
                msgBodiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        violet.gateway.common.proto_gen.im.MessageBody, violet.gateway.common.proto_gen.im.MessageBody.Builder, violet.gateway.common.proto_gen.im.MessageBodyOrBuilder>(
                        msgBodies_,
                        ((bitField0_ & 0x00000002) == 0x00000002),
                        getParentForChildren(),
                        isClean());
                msgBodies_ = null;
            }
            return msgBodiesBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:im.ConversationMessage)
    }

    // @@protoc_insertion_point(class_scope:im.ConversationMessage)
    private static final violet.gateway.common.proto_gen.im.ConversationMessage DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.im.ConversationMessage();
    }

    public static violet.gateway.common.proto_gen.im.ConversationMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConversationMessage>
            PARSER = new com.google.protobuf.AbstractParser<ConversationMessage>() {
        public ConversationMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ConversationMessage(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<ConversationMessage> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConversationMessage> getParserForType() {
        return PARSER;
    }

    public violet.gateway.common.proto_gen.im.ConversationMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

