// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf type {@code im.ConversationInfo}
 */
public final class ConversationInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:im.ConversationInfo)
        ConversationInfoOrBuilder {
    // Use ConversationInfo.newBuilder() to construct.
    private ConversationInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ConversationInfo() {
        conShortId_ = 0L;
        conId_ = "";
        conType_ = 0;
        userConIndex_ = 0L;
        badgeCount_ = 0L;
        isMember_ = false;
        members_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ConversationInfo(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        conShortId_ = input.readInt64();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        conId_ = s;
                        break;
                    }
                    case 24: {

                        conType_ = input.readInt32();
                        break;
                    }
                    case 32: {

                        userConIndex_ = input.readInt64();
                        break;
                    }
                    case 40: {

                        badgeCount_ = input.readInt64();
                        break;
                    }
                    case 48: {

                        isMember_ = input.readBool();
                        break;
                    }
                    case 58: {
                        if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                            members_ = new java.util.ArrayList<violet.gateway.common.proto_gen.im.ConversationUserInfo>();
                            mutable_bitField0_ |= 0x00000040;
                        }
                        members_.add(
                                input.readMessage(violet.gateway.common.proto_gen.im.ConversationUserInfo.parser(), extensionRegistry));
                        break;
                    }
                    case 66: {
                        violet.gateway.common.proto_gen.im.ConversationCoreInfo.Builder subBuilder = null;
                        if (conCoreInfo_ != null) {
                            subBuilder = conCoreInfo_.toBuilder();
                        }
                        conCoreInfo_ = input.readMessage(violet.gateway.common.proto_gen.im.ConversationCoreInfo.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(conCoreInfo_);
                            conCoreInfo_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 74: {
                        violet.gateway.common.proto_gen.im.ConversationSettingInfo.Builder subBuilder = null;
                        if (conSettingInfo_ != null) {
                            subBuilder = conSettingInfo_.toBuilder();
                        }
                        conSettingInfo_ = input.readMessage(violet.gateway.common.proto_gen.im.ConversationSettingInfo.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(conSettingInfo_);
                            conSettingInfo_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                members_ = java.util.Collections.unmodifiableList(members_);
            }
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        violet.gateway.common.proto_gen.im.ConversationInfo.class, violet.gateway.common.proto_gen.im.ConversationInfo.Builder.class);
    }

    private int bitField0_;
    public static final int CON_SHORT_ID_FIELD_NUMBER = 1;
    private long conShortId_;

    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public long getConShortId() {
        return conShortId_;
    }

    public static final int CON_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object conId_;

    /**
     * <code>string con_id = 2;</code>
     */
    public java.lang.String getConId() {
        java.lang.Object ref = conId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            conId_ = s;
            return s;
        }
    }

    /**
     * <code>string con_id = 2;</code>
     */
    public com.google.protobuf.ByteString
    getConIdBytes() {
        java.lang.Object ref = conId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            conId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CON_TYPE_FIELD_NUMBER = 3;
    private int conType_;

    /**
     * <code>int32 con_type = 3;</code>
     */
    public int getConType() {
        return conType_;
    }

    public static final int USER_CON_INDEX_FIELD_NUMBER = 4;
    private long userConIndex_;

    /**
     * <code>int64 user_con_index = 4;</code>
     */
    public long getUserConIndex() {
        return userConIndex_;
    }

    public static final int BADGE_COUNT_FIELD_NUMBER = 5;
    private long badgeCount_;

    /**
     * <code>int64 badge_count = 5;</code>
     */
    public long getBadgeCount() {
        return badgeCount_;
    }

    public static final int IS_MEMBER_FIELD_NUMBER = 6;
    private boolean isMember_;

    /**
     * <code>bool is_member = 6;</code>
     */
    public boolean getIsMember() {
        return isMember_;
    }

    public static final int MEMBERS_FIELD_NUMBER = 7;
    private java.util.List<violet.gateway.common.proto_gen.im.ConversationUserInfo> members_;

    /**
     * <code>repeated .im.ConversationUserInfo members = 7;</code>
     */
    public java.util.List<violet.gateway.common.proto_gen.im.ConversationUserInfo> getMembersList() {
        return members_;
    }

    /**
     * <code>repeated .im.ConversationUserInfo members = 7;</code>
     */
    public java.util.List<? extends violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder>
    getMembersOrBuilderList() {
        return members_;
    }

    /**
     * <code>repeated .im.ConversationUserInfo members = 7;</code>
     */
    public int getMembersCount() {
        return members_.size();
    }

    /**
     * <code>repeated .im.ConversationUserInfo members = 7;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationUserInfo getMembers(int index) {
        return members_.get(index);
    }

    /**
     * <code>repeated .im.ConversationUserInfo members = 7;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder getMembersOrBuilder(
            int index) {
        return members_.get(index);
    }

    public static final int CON_CORE_INFO_FIELD_NUMBER = 8;
    private violet.gateway.common.proto_gen.im.ConversationCoreInfo conCoreInfo_;

    /**
     * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
     */
    public boolean hasConCoreInfo() {
        return conCoreInfo_ != null;
    }

    /**
     * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationCoreInfo getConCoreInfo() {
        return conCoreInfo_ == null ? violet.gateway.common.proto_gen.im.ConversationCoreInfo.getDefaultInstance() : conCoreInfo_;
    }

    /**
     * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationCoreInfoOrBuilder getConCoreInfoOrBuilder() {
        return getConCoreInfo();
    }

    public static final int CON_SETTING_INFO_FIELD_NUMBER = 9;
    private violet.gateway.common.proto_gen.im.ConversationSettingInfo conSettingInfo_;

    /**
     * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
     */
    public boolean hasConSettingInfo() {
        return conSettingInfo_ != null;
    }

    /**
     * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationSettingInfo getConSettingInfo() {
        return conSettingInfo_ == null ? violet.gateway.common.proto_gen.im.ConversationSettingInfo.getDefaultInstance() : conSettingInfo_;
    }

    /**
     * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
     */
    public violet.gateway.common.proto_gen.im.ConversationSettingInfoOrBuilder getConSettingInfoOrBuilder() {
        return getConSettingInfo();
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (conShortId_ != 0L) {
            output.writeInt64(1, conShortId_);
        }
        if (!getConIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conId_);
        }
        if (conType_ != 0) {
            output.writeInt32(3, conType_);
        }
        if (userConIndex_ != 0L) {
            output.writeInt64(4, userConIndex_);
        }
        if (badgeCount_ != 0L) {
            output.writeInt64(5, badgeCount_);
        }
        if (isMember_ != false) {
            output.writeBool(6, isMember_);
        }
        for (int i = 0; i < members_.size(); i++) {
            output.writeMessage(7, members_.get(i));
        }
        if (conCoreInfo_ != null) {
            output.writeMessage(8, getConCoreInfo());
        }
        if (conSettingInfo_ != null) {
            output.writeMessage(9, getConSettingInfo());
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (conShortId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, conShortId_);
        }
        if (!getConIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conId_);
        }
        if (conType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, conType_);
        }
        if (userConIndex_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(4, userConIndex_);
        }
        if (badgeCount_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(5, badgeCount_);
        }
        if (isMember_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(6, isMember_);
        }
        for (int i = 0; i < members_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(7, members_.get(i));
        }
        if (conCoreInfo_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(8, getConCoreInfo());
        }
        if (conSettingInfo_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(9, getConSettingInfo());
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof violet.gateway.common.proto_gen.im.ConversationInfo)) {
            return super.equals(obj);
        }
        violet.gateway.common.proto_gen.im.ConversationInfo other = (violet.gateway.common.proto_gen.im.ConversationInfo) obj;

        boolean result = true;
        result = result && (getConShortId()
                == other.getConShortId());
        result = result && getConId()
                .equals(other.getConId());
        result = result && (getConType()
                == other.getConType());
        result = result && (getUserConIndex()
                == other.getUserConIndex());
        result = result && (getBadgeCount()
                == other.getBadgeCount());
        result = result && (getIsMember()
                == other.getIsMember());
        result = result && getMembersList()
                .equals(other.getMembersList());
        result = result && (hasConCoreInfo() == other.hasConCoreInfo());
        if (hasConCoreInfo()) {
            result = result && getConCoreInfo()
                    .equals(other.getConCoreInfo());
        }
        result = result && (hasConSettingInfo() == other.hasConSettingInfo());
        if (hasConSettingInfo()) {
            result = result && getConSettingInfo()
                    .equals(other.getConSettingInfo());
        }
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CON_SHORT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getConShortId());
        hash = (37 * hash) + CON_ID_FIELD_NUMBER;
        hash = (53 * hash) + getConId().hashCode();
        hash = (37 * hash) + CON_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getConType();
        hash = (37 * hash) + USER_CON_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getUserConIndex());
        hash = (37 * hash) + BADGE_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getBadgeCount());
        hash = (37 * hash) + IS_MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getIsMember());
        if (getMembersCount() > 0) {
            hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
            hash = (53 * hash) + getMembersList().hashCode();
        }
        if (hasConCoreInfo()) {
            hash = (37 * hash) + CON_CORE_INFO_FIELD_NUMBER;
            hash = (53 * hash) + getConCoreInfo().hashCode();
        }
        if (hasConSettingInfo()) {
            hash = (37 * hash) + CON_SETTING_INFO_FIELD_NUMBER;
            hash = (53 * hash) + getConSettingInfo().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(violet.gateway.common.proto_gen.im.ConversationInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code im.ConversationInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:im.ConversationInfo)
            violet.gateway.common.proto_gen.im.ConversationInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            violet.gateway.common.proto_gen.im.ConversationInfo.class, violet.gateway.common.proto_gen.im.ConversationInfo.Builder.class);
        }

        // Construct using violet.gateway.common.proto_gen.im.ConversationInfo.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getMembersFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            conShortId_ = 0L;

            conId_ = "";

            conType_ = 0;

            userConIndex_ = 0L;

            badgeCount_ = 0L;

            isMember_ = false;

            if (membersBuilder_ == null) {
                members_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000040);
            } else {
                membersBuilder_.clear();
            }
            if (conCoreInfoBuilder_ == null) {
                conCoreInfo_ = null;
            } else {
                conCoreInfo_ = null;
                conCoreInfoBuilder_ = null;
            }
            if (conSettingInfoBuilder_ == null) {
                conSettingInfo_ = null;
            } else {
                conSettingInfo_ = null;
                conSettingInfoBuilder_ = null;
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_ConversationInfo_descriptor;
        }

        public violet.gateway.common.proto_gen.im.ConversationInfo getDefaultInstanceForType() {
            return violet.gateway.common.proto_gen.im.ConversationInfo.getDefaultInstance();
        }

        public violet.gateway.common.proto_gen.im.ConversationInfo build() {
            violet.gateway.common.proto_gen.im.ConversationInfo result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public violet.gateway.common.proto_gen.im.ConversationInfo buildPartial() {
            violet.gateway.common.proto_gen.im.ConversationInfo result = new violet.gateway.common.proto_gen.im.ConversationInfo(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.conShortId_ = conShortId_;
            result.conId_ = conId_;
            result.conType_ = conType_;
            result.userConIndex_ = userConIndex_;
            result.badgeCount_ = badgeCount_;
            result.isMember_ = isMember_;
            if (membersBuilder_ == null) {
                if (((bitField0_ & 0x00000040) == 0x00000040)) {
                    members_ = java.util.Collections.unmodifiableList(members_);
                    bitField0_ = (bitField0_ & ~0x00000040);
                }
                result.members_ = members_;
            } else {
                result.members_ = membersBuilder_.build();
            }
            if (conCoreInfoBuilder_ == null) {
                result.conCoreInfo_ = conCoreInfo_;
            } else {
                result.conCoreInfo_ = conCoreInfoBuilder_.build();
            }
            if (conSettingInfoBuilder_ == null) {
                result.conSettingInfo_ = conSettingInfo_;
            } else {
                result.conSettingInfo_ = conSettingInfoBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof violet.gateway.common.proto_gen.im.ConversationInfo) {
                return mergeFrom((violet.gateway.common.proto_gen.im.ConversationInfo) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(violet.gateway.common.proto_gen.im.ConversationInfo other) {
            if (other == violet.gateway.common.proto_gen.im.ConversationInfo.getDefaultInstance()) return this;
            if (other.getConShortId() != 0L) {
                setConShortId(other.getConShortId());
            }
            if (!other.getConId().isEmpty()) {
                conId_ = other.conId_;
                onChanged();
            }
            if (other.getConType() != 0) {
                setConType(other.getConType());
            }
            if (other.getUserConIndex() != 0L) {
                setUserConIndex(other.getUserConIndex());
            }
            if (other.getBadgeCount() != 0L) {
                setBadgeCount(other.getBadgeCount());
            }
            if (other.getIsMember() != false) {
                setIsMember(other.getIsMember());
            }
            if (membersBuilder_ == null) {
                if (!other.members_.isEmpty()) {
                    if (members_.isEmpty()) {
                        members_ = other.members_;
                        bitField0_ = (bitField0_ & ~0x00000040);
                    } else {
                        ensureMembersIsMutable();
                        members_.addAll(other.members_);
                    }
                    onChanged();
                }
            } else {
                if (!other.members_.isEmpty()) {
                    if (membersBuilder_.isEmpty()) {
                        membersBuilder_.dispose();
                        membersBuilder_ = null;
                        members_ = other.members_;
                        bitField0_ = (bitField0_ & ~0x00000040);
                        membersBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getMembersFieldBuilder() : null;
                    } else {
                        membersBuilder_.addAllMessages(other.members_);
                    }
                }
            }
            if (other.hasConCoreInfo()) {
                mergeConCoreInfo(other.getConCoreInfo());
            }
            if (other.hasConSettingInfo()) {
                mergeConSettingInfo(other.getConSettingInfo());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            violet.gateway.common.proto_gen.im.ConversationInfo parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (violet.gateway.common.proto_gen.im.ConversationInfo) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private long conShortId_;

        /**
         * <code>int64 con_short_id = 1;</code>
         */
        public long getConShortId() {
            return conShortId_;
        }

        /**
         * <code>int64 con_short_id = 1;</code>
         */
        public Builder setConShortId(long value) {

            conShortId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 con_short_id = 1;</code>
         */
        public Builder clearConShortId() {

            conShortId_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object conId_ = "";

        /**
         * <code>string con_id = 2;</code>
         */
        public java.lang.String getConId() {
            java.lang.Object ref = conId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                conId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string con_id = 2;</code>
         */
        public com.google.protobuf.ByteString
        getConIdBytes() {
            java.lang.Object ref = conId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                conId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string con_id = 2;</code>
         */
        public Builder setConId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            conId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string con_id = 2;</code>
         */
        public Builder clearConId() {

            conId_ = getDefaultInstance().getConId();
            onChanged();
            return this;
        }

        /**
         * <code>string con_id = 2;</code>
         */
        public Builder setConIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            conId_ = value;
            onChanged();
            return this;
        }

        private int conType_;

        /**
         * <code>int32 con_type = 3;</code>
         */
        public int getConType() {
            return conType_;
        }

        /**
         * <code>int32 con_type = 3;</code>
         */
        public Builder setConType(int value) {

            conType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 con_type = 3;</code>
         */
        public Builder clearConType() {

            conType_ = 0;
            onChanged();
            return this;
        }

        private long userConIndex_;

        /**
         * <code>int64 user_con_index = 4;</code>
         */
        public long getUserConIndex() {
            return userConIndex_;
        }

        /**
         * <code>int64 user_con_index = 4;</code>
         */
        public Builder setUserConIndex(long value) {

            userConIndex_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 user_con_index = 4;</code>
         */
        public Builder clearUserConIndex() {

            userConIndex_ = 0L;
            onChanged();
            return this;
        }

        private long badgeCount_;

        /**
         * <code>int64 badge_count = 5;</code>
         */
        public long getBadgeCount() {
            return badgeCount_;
        }

        /**
         * <code>int64 badge_count = 5;</code>
         */
        public Builder setBadgeCount(long value) {

            badgeCount_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 badge_count = 5;</code>
         */
        public Builder clearBadgeCount() {

            badgeCount_ = 0L;
            onChanged();
            return this;
        }

        private boolean isMember_;

        /**
         * <code>bool is_member = 6;</code>
         */
        public boolean getIsMember() {
            return isMember_;
        }

        /**
         * <code>bool is_member = 6;</code>
         */
        public Builder setIsMember(boolean value) {

            isMember_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bool is_member = 6;</code>
         */
        public Builder clearIsMember() {

            isMember_ = false;
            onChanged();
            return this;
        }

        private java.util.List<violet.gateway.common.proto_gen.im.ConversationUserInfo> members_ =
                java.util.Collections.emptyList();

        private void ensureMembersIsMutable() {
            if (!((bitField0_ & 0x00000040) == 0x00000040)) {
                members_ = new java.util.ArrayList<violet.gateway.common.proto_gen.im.ConversationUserInfo>(members_);
                bitField0_ |= 0x00000040;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationUserInfo, violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder, violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder> membersBuilder_;

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public java.util.List<violet.gateway.common.proto_gen.im.ConversationUserInfo> getMembersList() {
            if (membersBuilder_ == null) {
                return java.util.Collections.unmodifiableList(members_);
            } else {
                return membersBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public int getMembersCount() {
            if (membersBuilder_ == null) {
                return members_.size();
            } else {
                return membersBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationUserInfo getMembers(int index) {
            if (membersBuilder_ == null) {
                return members_.get(index);
            } else {
                return membersBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder setMembers(
                int index, violet.gateway.common.proto_gen.im.ConversationUserInfo value) {
            if (membersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureMembersIsMutable();
                members_.set(index, value);
                onChanged();
            } else {
                membersBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder setMembers(
                int index, violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder builderForValue) {
            if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                members_.set(index, builderForValue.build());
                onChanged();
            } else {
                membersBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder addMembers(violet.gateway.common.proto_gen.im.ConversationUserInfo value) {
            if (membersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureMembersIsMutable();
                members_.add(value);
                onChanged();
            } else {
                membersBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder addMembers(
                int index, violet.gateway.common.proto_gen.im.ConversationUserInfo value) {
            if (membersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureMembersIsMutable();
                members_.add(index, value);
                onChanged();
            } else {
                membersBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder addMembers(
                violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder builderForValue) {
            if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                members_.add(builderForValue.build());
                onChanged();
            } else {
                membersBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder addMembers(
                int index, violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder builderForValue) {
            if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                members_.add(index, builderForValue.build());
                onChanged();
            } else {
                membersBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder addAllMembers(
                java.lang.Iterable<? extends violet.gateway.common.proto_gen.im.ConversationUserInfo> values) {
            if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, members_);
                onChanged();
            } else {
                membersBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder clearMembers() {
            if (membersBuilder_ == null) {
                members_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000040);
                onChanged();
            } else {
                membersBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public Builder removeMembers(int index) {
            if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                members_.remove(index);
                onChanged();
            } else {
                membersBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder getMembersBuilder(
                int index) {
            return getMembersFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder getMembersOrBuilder(
                int index) {
            if (membersBuilder_ == null) {
                return members_.get(index);
            } else {
                return membersBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public java.util.List<? extends violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder>
        getMembersOrBuilderList() {
            if (membersBuilder_ != null) {
                return membersBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(members_);
            }
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder addMembersBuilder() {
            return getMembersFieldBuilder().addBuilder(
                    violet.gateway.common.proto_gen.im.ConversationUserInfo.getDefaultInstance());
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder addMembersBuilder(
                int index) {
            return getMembersFieldBuilder().addBuilder(
                    index, violet.gateway.common.proto_gen.im.ConversationUserInfo.getDefaultInstance());
        }

        /**
         * <code>repeated .im.ConversationUserInfo members = 7;</code>
         */
        public java.util.List<violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder>
        getMembersBuilderList() {
            return getMembersFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationUserInfo, violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder, violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder>
        getMembersFieldBuilder() {
            if (membersBuilder_ == null) {
                membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        violet.gateway.common.proto_gen.im.ConversationUserInfo, violet.gateway.common.proto_gen.im.ConversationUserInfo.Builder, violet.gateway.common.proto_gen.im.ConversationUserInfoOrBuilder>(
                        members_,
                        ((bitField0_ & 0x00000040) == 0x00000040),
                        getParentForChildren(),
                        isClean());
                members_ = null;
            }
            return membersBuilder_;
        }

        private violet.gateway.common.proto_gen.im.ConversationCoreInfo conCoreInfo_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationCoreInfo, violet.gateway.common.proto_gen.im.ConversationCoreInfo.Builder, violet.gateway.common.proto_gen.im.ConversationCoreInfoOrBuilder> conCoreInfoBuilder_;

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public boolean hasConCoreInfo() {
            return conCoreInfoBuilder_ != null || conCoreInfo_ != null;
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationCoreInfo getConCoreInfo() {
            if (conCoreInfoBuilder_ == null) {
                return conCoreInfo_ == null ? violet.gateway.common.proto_gen.im.ConversationCoreInfo.getDefaultInstance() : conCoreInfo_;
            } else {
                return conCoreInfoBuilder_.getMessage();
            }
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public Builder setConCoreInfo(violet.gateway.common.proto_gen.im.ConversationCoreInfo value) {
            if (conCoreInfoBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                conCoreInfo_ = value;
                onChanged();
            } else {
                conCoreInfoBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public Builder setConCoreInfo(
                violet.gateway.common.proto_gen.im.ConversationCoreInfo.Builder builderForValue) {
            if (conCoreInfoBuilder_ == null) {
                conCoreInfo_ = builderForValue.build();
                onChanged();
            } else {
                conCoreInfoBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public Builder mergeConCoreInfo(violet.gateway.common.proto_gen.im.ConversationCoreInfo value) {
            if (conCoreInfoBuilder_ == null) {
                if (conCoreInfo_ != null) {
                    conCoreInfo_ =
                            violet.gateway.common.proto_gen.im.ConversationCoreInfo.newBuilder(conCoreInfo_).mergeFrom(value).buildPartial();
                } else {
                    conCoreInfo_ = value;
                }
                onChanged();
            } else {
                conCoreInfoBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public Builder clearConCoreInfo() {
            if (conCoreInfoBuilder_ == null) {
                conCoreInfo_ = null;
                onChanged();
            } else {
                conCoreInfo_ = null;
                conCoreInfoBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationCoreInfo.Builder getConCoreInfoBuilder() {

            onChanged();
            return getConCoreInfoFieldBuilder().getBuilder();
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationCoreInfoOrBuilder getConCoreInfoOrBuilder() {
            if (conCoreInfoBuilder_ != null) {
                return conCoreInfoBuilder_.getMessageOrBuilder();
            } else {
                return conCoreInfo_ == null ?
                        violet.gateway.common.proto_gen.im.ConversationCoreInfo.getDefaultInstance() : conCoreInfo_;
            }
        }

        /**
         * <code>.im.ConversationCoreInfo con_core_info = 8;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationCoreInfo, violet.gateway.common.proto_gen.im.ConversationCoreInfo.Builder, violet.gateway.common.proto_gen.im.ConversationCoreInfoOrBuilder>
        getConCoreInfoFieldBuilder() {
            if (conCoreInfoBuilder_ == null) {
                conCoreInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        violet.gateway.common.proto_gen.im.ConversationCoreInfo, violet.gateway.common.proto_gen.im.ConversationCoreInfo.Builder, violet.gateway.common.proto_gen.im.ConversationCoreInfoOrBuilder>(
                        getConCoreInfo(),
                        getParentForChildren(),
                        isClean());
                conCoreInfo_ = null;
            }
            return conCoreInfoBuilder_;
        }

        private violet.gateway.common.proto_gen.im.ConversationSettingInfo conSettingInfo_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationSettingInfo, violet.gateway.common.proto_gen.im.ConversationSettingInfo.Builder, violet.gateway.common.proto_gen.im.ConversationSettingInfoOrBuilder> conSettingInfoBuilder_;

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public boolean hasConSettingInfo() {
            return conSettingInfoBuilder_ != null || conSettingInfo_ != null;
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationSettingInfo getConSettingInfo() {
            if (conSettingInfoBuilder_ == null) {
                return conSettingInfo_ == null ? violet.gateway.common.proto_gen.im.ConversationSettingInfo.getDefaultInstance() : conSettingInfo_;
            } else {
                return conSettingInfoBuilder_.getMessage();
            }
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public Builder setConSettingInfo(violet.gateway.common.proto_gen.im.ConversationSettingInfo value) {
            if (conSettingInfoBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                conSettingInfo_ = value;
                onChanged();
            } else {
                conSettingInfoBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public Builder setConSettingInfo(
                violet.gateway.common.proto_gen.im.ConversationSettingInfo.Builder builderForValue) {
            if (conSettingInfoBuilder_ == null) {
                conSettingInfo_ = builderForValue.build();
                onChanged();
            } else {
                conSettingInfoBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public Builder mergeConSettingInfo(violet.gateway.common.proto_gen.im.ConversationSettingInfo value) {
            if (conSettingInfoBuilder_ == null) {
                if (conSettingInfo_ != null) {
                    conSettingInfo_ =
                            violet.gateway.common.proto_gen.im.ConversationSettingInfo.newBuilder(conSettingInfo_).mergeFrom(value).buildPartial();
                } else {
                    conSettingInfo_ = value;
                }
                onChanged();
            } else {
                conSettingInfoBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public Builder clearConSettingInfo() {
            if (conSettingInfoBuilder_ == null) {
                conSettingInfo_ = null;
                onChanged();
            } else {
                conSettingInfo_ = null;
                conSettingInfoBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationSettingInfo.Builder getConSettingInfoBuilder() {

            onChanged();
            return getConSettingInfoFieldBuilder().getBuilder();
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        public violet.gateway.common.proto_gen.im.ConversationSettingInfoOrBuilder getConSettingInfoOrBuilder() {
            if (conSettingInfoBuilder_ != null) {
                return conSettingInfoBuilder_.getMessageOrBuilder();
            } else {
                return conSettingInfo_ == null ?
                        violet.gateway.common.proto_gen.im.ConversationSettingInfo.getDefaultInstance() : conSettingInfo_;
            }
        }

        /**
         * <code>.im.ConversationSettingInfo con_setting_info = 9;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                violet.gateway.common.proto_gen.im.ConversationSettingInfo, violet.gateway.common.proto_gen.im.ConversationSettingInfo.Builder, violet.gateway.common.proto_gen.im.ConversationSettingInfoOrBuilder>
        getConSettingInfoFieldBuilder() {
            if (conSettingInfoBuilder_ == null) {
                conSettingInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        violet.gateway.common.proto_gen.im.ConversationSettingInfo, violet.gateway.common.proto_gen.im.ConversationSettingInfo.Builder, violet.gateway.common.proto_gen.im.ConversationSettingInfoOrBuilder>(
                        getConSettingInfo(),
                        getParentForChildren(),
                        isClean());
                conSettingInfo_ = null;
            }
            return conSettingInfoBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:im.ConversationInfo)
    }

    // @@protoc_insertion_point(class_scope:im.ConversationInfo)
    private static final violet.gateway.common.proto_gen.im.ConversationInfo DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.im.ConversationInfo();
    }

    public static violet.gateway.common.proto_gen.im.ConversationInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConversationInfo>
            PARSER = new com.google.protobuf.AbstractParser<ConversationInfo>() {
        public ConversationInfo parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ConversationInfo(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<ConversationInfo> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConversationInfo> getParserForType() {
        return PARSER;
    }

    public violet.gateway.common.proto_gen.im.ConversationInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

