// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf type {@code im.CreateConversationRequest}
 */
public  final class CreateConversationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.CreateConversationRequest)
    CreateConversationRequestOrBuilder {
  // Use CreateConversationRequest.newBuilder() to construct.
  private CreateConversationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConversationRequest() {
    conId_ = "";
    conType_ = 0;
    name_ = "";
    avatarUri_ = "";
    description_ = "";
    notice_ = "";
    ownerId_ = 0L;
    members_ = java.util.Collections.emptyList();
    extra_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CreateConversationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            conId_ = s;
            break;
          }
          case 16: {

            conType_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            avatarUri_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            notice_ = s;
            break;
          }
          case 56: {

            ownerId_ = input.readInt64();
            break;
          }
          case 64: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              members_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000080;
            }
            members_.add(input.readInt64());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
              members_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000080;
            }
            while (input.getBytesUntilLimit() > 0) {
              members_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            extra_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        members_ = java.util.Collections.unmodifiableList(members_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return violet.gateway.common.proto_gen.im.Im.internal_static_im_CreateConversationRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return violet.gateway.common.proto_gen.im.Im.internal_static_im_CreateConversationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            violet.gateway.common.proto_gen.im.CreateConversationRequest.class, violet.gateway.common.proto_gen.im.CreateConversationRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CON_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object conId_;
  /**
   * <code>string con_id = 1;</code>
   */
  public java.lang.String getConId() {
    java.lang.Object ref = conId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conId_ = s;
      return s;
    }
  }
  /**
   * <code>string con_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getConIdBytes() {
    java.lang.Object ref = conId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CON_TYPE_FIELD_NUMBER = 2;
  private int conType_;
  /**
   * <code>int32 con_type = 2;</code>
   */
  public int getConType() {
    return conType_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_URI_FIELD_NUMBER = 4;
  private volatile java.lang.Object avatarUri_;
  /**
   * <code>string avatar_uri = 4;</code>
   */
  public java.lang.String getAvatarUri() {
    java.lang.Object ref = avatarUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatarUri_ = s;
      return s;
    }
  }
  /**
   * <code>string avatar_uri = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAvatarUriBytes() {
    java.lang.Object ref = avatarUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatarUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 5;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTICE_FIELD_NUMBER = 6;
  private volatile java.lang.Object notice_;
  /**
   * <code>string notice = 6;</code>
   */
  public java.lang.String getNotice() {
    java.lang.Object ref = notice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notice_ = s;
      return s;
    }
  }
  /**
   * <code>string notice = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNoticeBytes() {
    java.lang.Object ref = notice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_ID_FIELD_NUMBER = 7;
  private long ownerId_;
  /**
   * <code>int64 owner_id = 7;</code>
   */
  public long getOwnerId() {
    return ownerId_;
  }

  public static final int MEMBERS_FIELD_NUMBER = 8;
  private java.util.List<java.lang.Long> members_;
  /**
   * <code>repeated int64 members = 8;</code>
   */
  public java.util.List<java.lang.Long>
      getMembersList() {
    return members_;
  }
  /**
   * <code>repeated int64 members = 8;</code>
   */
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated int64 members = 8;</code>
   */
  public long getMembers(int index) {
    return members_.get(index);
  }
  private int membersMemoizedSerializedSize = -1;

  public static final int EXTRA_FIELD_NUMBER = 9;
  private volatile java.lang.Object extra_;
  /**
   * <code>string extra = 9;</code>
   */
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <code>string extra = 9;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getConIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, conId_);
    }
    if (conType_ != 0) {
      output.writeInt32(2, conType_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!getAvatarUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, avatarUri_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    if (!getNoticeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, notice_);
    }
    if (ownerId_ != 0L) {
      output.writeInt64(7, ownerId_);
    }
    if (getMembersList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(membersMemoizedSerializedSize);
    }
    for (int i = 0; i < members_.size(); i++) {
      output.writeInt64NoTag(members_.get(i));
    }
    if (!getExtraBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, extra_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, conId_);
    }
    if (conType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, conType_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!getAvatarUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, avatarUri_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    if (!getNoticeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, notice_);
    }
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, ownerId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < members_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(members_.get(i));
      }
      size += dataSize;
      if (!getMembersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      membersMemoizedSerializedSize = dataSize;
    }
    if (!getExtraBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, extra_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof violet.gateway.common.proto_gen.im.CreateConversationRequest)) {
      return super.equals(obj);
    }
    violet.gateway.common.proto_gen.im.CreateConversationRequest other = (violet.gateway.common.proto_gen.im.CreateConversationRequest) obj;

    boolean result = true;
    result = result && getConId()
        .equals(other.getConId());
    result = result && (getConType()
        == other.getConType());
    result = result && getName()
        .equals(other.getName());
    result = result && getAvatarUri()
        .equals(other.getAvatarUri());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getNotice()
        .equals(other.getNotice());
    result = result && (getOwnerId()
        == other.getOwnerId());
    result = result && getMembersList()
        .equals(other.getMembersList());
    result = result && getExtra()
        .equals(other.getExtra());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CON_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConId().hashCode();
    hash = (37 * hash) + CON_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getConType();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AVATAR_URI_FIELD_NUMBER;
    hash = (53 * hash) + getAvatarUri().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + NOTICE_FIELD_NUMBER;
    hash = (53 * hash) + getNotice().hashCode();
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOwnerId());
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.CreateConversationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(violet.gateway.common.proto_gen.im.CreateConversationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.CreateConversationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.CreateConversationRequest)
      violet.gateway.common.proto_gen.im.CreateConversationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_CreateConversationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_CreateConversationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              violet.gateway.common.proto_gen.im.CreateConversationRequest.class, violet.gateway.common.proto_gen.im.CreateConversationRequest.Builder.class);
    }

    // Construct using violet.gateway.common.proto_gen.im.CreateConversationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      conId_ = "";

      conType_ = 0;

      name_ = "";

      avatarUri_ = "";

      description_ = "";

      notice_ = "";

      ownerId_ = 0L;

      members_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      extra_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_CreateConversationRequest_descriptor;
    }

    public violet.gateway.common.proto_gen.im.CreateConversationRequest getDefaultInstanceForType() {
      return violet.gateway.common.proto_gen.im.CreateConversationRequest.getDefaultInstance();
    }

    public violet.gateway.common.proto_gen.im.CreateConversationRequest build() {
      violet.gateway.common.proto_gen.im.CreateConversationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public violet.gateway.common.proto_gen.im.CreateConversationRequest buildPartial() {
      violet.gateway.common.proto_gen.im.CreateConversationRequest result = new violet.gateway.common.proto_gen.im.CreateConversationRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.conId_ = conId_;
      result.conType_ = conType_;
      result.name_ = name_;
      result.avatarUri_ = avatarUri_;
      result.description_ = description_;
      result.notice_ = notice_;
      result.ownerId_ = ownerId_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        members_ = java.util.Collections.unmodifiableList(members_);
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.members_ = members_;
      result.extra_ = extra_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof violet.gateway.common.proto_gen.im.CreateConversationRequest) {
        return mergeFrom((violet.gateway.common.proto_gen.im.CreateConversationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(violet.gateway.common.proto_gen.im.CreateConversationRequest other) {
      if (other == violet.gateway.common.proto_gen.im.CreateConversationRequest.getDefaultInstance()) return this;
      if (!other.getConId().isEmpty()) {
        conId_ = other.conId_;
        onChanged();
      }
      if (other.getConType() != 0) {
        setConType(other.getConType());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getAvatarUri().isEmpty()) {
        avatarUri_ = other.avatarUri_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getNotice().isEmpty()) {
        notice_ = other.notice_;
        onChanged();
      }
      if (other.getOwnerId() != 0L) {
        setOwnerId(other.getOwnerId());
      }
      if (!other.members_.isEmpty()) {
        if (members_.isEmpty()) {
          members_ = other.members_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureMembersIsMutable();
          members_.addAll(other.members_);
        }
        onChanged();
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      violet.gateway.common.proto_gen.im.CreateConversationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (violet.gateway.common.proto_gen.im.CreateConversationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object conId_ = "";
    /**
     * <code>string con_id = 1;</code>
     */
    public java.lang.String getConId() {
      java.lang.Object ref = conId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string con_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getConIdBytes() {
      java.lang.Object ref = conId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string con_id = 1;</code>
     */
    public Builder setConId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string con_id = 1;</code>
     */
    public Builder clearConId() {
      
      conId_ = getDefaultInstance().getConId();
      onChanged();
      return this;
    }
    /**
     * <code>string con_id = 1;</code>
     */
    public Builder setConIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conId_ = value;
      onChanged();
      return this;
    }

    private int conType_ ;
    /**
     * <code>int32 con_type = 2;</code>
     */
    public int getConType() {
      return conType_;
    }
    /**
     * <code>int32 con_type = 2;</code>
     */
    public Builder setConType(int value) {
      
      conType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 con_type = 2;</code>
     */
    public Builder clearConType() {
      
      conType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object avatarUri_ = "";
    /**
     * <code>string avatar_uri = 4;</code>
     */
    public java.lang.String getAvatarUri() {
      java.lang.Object ref = avatarUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avatar_uri = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarUriBytes() {
      java.lang.Object ref = avatarUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avatar_uri = 4;</code>
     */
    public Builder setAvatarUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatarUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string avatar_uri = 4;</code>
     */
    public Builder clearAvatarUri() {
      
      avatarUri_ = getDefaultInstance().getAvatarUri();
      onChanged();
      return this;
    }
    /**
     * <code>string avatar_uri = 4;</code>
     */
    public Builder setAvatarUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatarUri_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 5;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notice_ = "";
    /**
     * <code>string notice = 6;</code>
     */
    public java.lang.String getNotice() {
      java.lang.Object ref = notice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string notice = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNoticeBytes() {
      java.lang.Object ref = notice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string notice = 6;</code>
     */
    public Builder setNotice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string notice = 6;</code>
     */
    public Builder clearNotice() {
      
      notice_ = getDefaultInstance().getNotice();
      onChanged();
      return this;
    }
    /**
     * <code>string notice = 6;</code>
     */
    public Builder setNoticeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notice_ = value;
      onChanged();
      return this;
    }

    private long ownerId_ ;
    /**
     * <code>int64 owner_id = 7;</code>
     */
    public long getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>int64 owner_id = 7;</code>
     */
    public Builder setOwnerId(long value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 owner_id = 7;</code>
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> members_ = java.util.Collections.emptyList();
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        members_ = new java.util.ArrayList<java.lang.Long>(members_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public java.util.List<java.lang.Long>
        getMembersList() {
      return java.util.Collections.unmodifiableList(members_);
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public long getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public Builder setMembers(
        int index, long value) {
      ensureMembersIsMutable();
      members_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public Builder addMembers(long value) {
      ensureMembersIsMutable();
      members_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public Builder addAllMembers(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureMembersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, members_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 members = 8;</code>
     */
    public Builder clearMembers() {
      members_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <code>string extra = 9;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extra = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extra = 9;</code>
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 9;</code>
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 9;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:im.CreateConversationRequest)
  }

  // @@protoc_insertion_point(class_scope:im.CreateConversationRequest)
  private static final violet.gateway.common.proto_gen.im.CreateConversationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.im.CreateConversationRequest();
  }

  public static violet.gateway.common.proto_gen.im.CreateConversationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConversationRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateConversationRequest>() {
    public CreateConversationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateConversationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateConversationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConversationRequest> getParserForType() {
    return PARSER;
  }

  public violet.gateway.common.proto_gen.im.CreateConversationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

