// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf type {@code im.GetConversationMembersRequest}
 */
public  final class GetConversationMembersRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.GetConversationMembersRequest)
    GetConversationMembersRequestOrBuilder {
  // Use GetConversationMembersRequest.newBuilder() to construct.
  private GetConversationMembersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetConversationMembersRequest() {
    conShortId_ = 0L;
    cursor_ = 0L;
    limit_ = 0L;
    onlyId_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetConversationMembersRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            conShortId_ = input.readInt64();
            break;
          }
          case 16: {

            cursor_ = input.readInt64();
            break;
          }
          case 24: {

            limit_ = input.readInt64();
            break;
          }
          case 32: {

            onlyId_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return violet.gateway.common.proto_gen.im.Im.internal_static_im_GetConversationMembersRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return violet.gateway.common.proto_gen.im.Im.internal_static_im_GetConversationMembersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            violet.gateway.common.proto_gen.im.GetConversationMembersRequest.class, violet.gateway.common.proto_gen.im.GetConversationMembersRequest.Builder.class);
  }

  public static final int CON_SHORT_ID_FIELD_NUMBER = 1;
  private long conShortId_;
  /**
   * <code>int64 con_short_id = 1;</code>
   */
  public long getConShortId() {
    return conShortId_;
  }

  public static final int CURSOR_FIELD_NUMBER = 2;
  private long cursor_;
  /**
   * <code>int64 cursor = 2;</code>
   */
  public long getCursor() {
    return cursor_;
  }

  public static final int LIMIT_FIELD_NUMBER = 3;
  private long limit_;
  /**
   * <code>int64 limit = 3;</code>
   */
  public long getLimit() {
    return limit_;
  }

  public static final int ONLY_ID_FIELD_NUMBER = 4;
  private boolean onlyId_;
  /**
   * <code>bool only_id = 4;</code>
   */
  public boolean getOnlyId() {
    return onlyId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (conShortId_ != 0L) {
      output.writeInt64(1, conShortId_);
    }
    if (cursor_ != 0L) {
      output.writeInt64(2, cursor_);
    }
    if (limit_ != 0L) {
      output.writeInt64(3, limit_);
    }
    if (onlyId_ != false) {
      output.writeBool(4, onlyId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (conShortId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, conShortId_);
    }
    if (cursor_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, cursor_);
    }
    if (limit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, limit_);
    }
    if (onlyId_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, onlyId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof violet.gateway.common.proto_gen.im.GetConversationMembersRequest)) {
      return super.equals(obj);
    }
    violet.gateway.common.proto_gen.im.GetConversationMembersRequest other = (violet.gateway.common.proto_gen.im.GetConversationMembersRequest) obj;

    boolean result = true;
    result = result && (getConShortId()
        == other.getConShortId());
    result = result && (getCursor()
        == other.getCursor());
    result = result && (getLimit()
        == other.getLimit());
    result = result && (getOnlyId()
        == other.getOnlyId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CON_SHORT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getConShortId());
    hash = (37 * hash) + CURSOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCursor());
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLimit());
    hash = (37 * hash) + ONLY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOnlyId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(violet.gateway.common.proto_gen.im.GetConversationMembersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.GetConversationMembersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.GetConversationMembersRequest)
      violet.gateway.common.proto_gen.im.GetConversationMembersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_GetConversationMembersRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_GetConversationMembersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              violet.gateway.common.proto_gen.im.GetConversationMembersRequest.class, violet.gateway.common.proto_gen.im.GetConversationMembersRequest.Builder.class);
    }

    // Construct using violet.gateway.common.proto_gen.im.GetConversationMembersRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      conShortId_ = 0L;

      cursor_ = 0L;

      limit_ = 0L;

      onlyId_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return violet.gateway.common.proto_gen.im.Im.internal_static_im_GetConversationMembersRequest_descriptor;
    }

    public violet.gateway.common.proto_gen.im.GetConversationMembersRequest getDefaultInstanceForType() {
      return violet.gateway.common.proto_gen.im.GetConversationMembersRequest.getDefaultInstance();
    }

    public violet.gateway.common.proto_gen.im.GetConversationMembersRequest build() {
      violet.gateway.common.proto_gen.im.GetConversationMembersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public violet.gateway.common.proto_gen.im.GetConversationMembersRequest buildPartial() {
      violet.gateway.common.proto_gen.im.GetConversationMembersRequest result = new violet.gateway.common.proto_gen.im.GetConversationMembersRequest(this);
      result.conShortId_ = conShortId_;
      result.cursor_ = cursor_;
      result.limit_ = limit_;
      result.onlyId_ = onlyId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof violet.gateway.common.proto_gen.im.GetConversationMembersRequest) {
        return mergeFrom((violet.gateway.common.proto_gen.im.GetConversationMembersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(violet.gateway.common.proto_gen.im.GetConversationMembersRequest other) {
      if (other == violet.gateway.common.proto_gen.im.GetConversationMembersRequest.getDefaultInstance()) return this;
      if (other.getConShortId() != 0L) {
        setConShortId(other.getConShortId());
      }
      if (other.getCursor() != 0L) {
        setCursor(other.getCursor());
      }
      if (other.getLimit() != 0L) {
        setLimit(other.getLimit());
      }
      if (other.getOnlyId() != false) {
        setOnlyId(other.getOnlyId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      violet.gateway.common.proto_gen.im.GetConversationMembersRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (violet.gateway.common.proto_gen.im.GetConversationMembersRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long conShortId_ ;
    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public long getConShortId() {
      return conShortId_;
    }
    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public Builder setConShortId(long value) {
      
      conShortId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 con_short_id = 1;</code>
     */
    public Builder clearConShortId() {
      
      conShortId_ = 0L;
      onChanged();
      return this;
    }

    private long cursor_ ;
    /**
     * <code>int64 cursor = 2;</code>
     */
    public long getCursor() {
      return cursor_;
    }
    /**
     * <code>int64 cursor = 2;</code>
     */
    public Builder setCursor(long value) {
      
      cursor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cursor = 2;</code>
     */
    public Builder clearCursor() {
      
      cursor_ = 0L;
      onChanged();
      return this;
    }

    private long limit_ ;
    /**
     * <code>int64 limit = 3;</code>
     */
    public long getLimit() {
      return limit_;
    }
    /**
     * <code>int64 limit = 3;</code>
     */
    public Builder setLimit(long value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 limit = 3;</code>
     */
    public Builder clearLimit() {
      
      limit_ = 0L;
      onChanged();
      return this;
    }

    private boolean onlyId_ ;
    /**
     * <code>bool only_id = 4;</code>
     */
    public boolean getOnlyId() {
      return onlyId_;
    }
    /**
     * <code>bool only_id = 4;</code>
     */
    public Builder setOnlyId(boolean value) {
      
      onlyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool only_id = 4;</code>
     */
    public Builder clearOnlyId() {
      
      onlyId_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:im.GetConversationMembersRequest)
  }

  // @@protoc_insertion_point(class_scope:im.GetConversationMembersRequest)
  private static final violet.gateway.common.proto_gen.im.GetConversationMembersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.im.GetConversationMembersRequest();
  }

  public static violet.gateway.common.proto_gen.im.GetConversationMembersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetConversationMembersRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetConversationMembersRequest>() {
    public GetConversationMembersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetConversationMembersRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetConversationMembersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetConversationMembersRequest> getParserForType() {
    return PARSER;
  }

  public violet.gateway.common.proto_gen.im.GetConversationMembersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

