// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

public interface GetMessageByConversationResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:im.GetMessageByConversationResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .im.MessageBody msg_bodies = 1;</code>
     */
    java.util.List<violet.gateway.common.proto_gen.im.MessageBody>
    getMsgBodiesList();

    /**
     * <code>repeated .im.MessageBody msg_bodies = 1;</code>
     */
    violet.gateway.common.proto_gen.im.MessageBody getMsgBodies(int index);

    /**
     * <code>repeated .im.MessageBody msg_bodies = 1;</code>
     */
    int getMsgBodiesCount();

    /**
     * <code>repeated .im.MessageBody msg_bodies = 1;</code>
     */
    java.util.List<? extends violet.gateway.common.proto_gen.im.MessageBodyOrBuilder>
    getMsgBodiesOrBuilderList();

    /**
     * <code>repeated .im.MessageBody msg_bodies = 1;</code>
     */
    violet.gateway.common.proto_gen.im.MessageBodyOrBuilder getMsgBodiesOrBuilder(
            int index);

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    boolean hasBaseResp();

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    violet.gateway.common.proto_gen.common.BaseResp getBaseResp();

    /**
     * <code>.common.BaseResp baseResp = 255;</code>
     */
    violet.gateway.common.proto_gen.common.BaseRespOrBuilder getBaseRespOrBuilder();
}
