// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

public interface GetMessageByInitRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:im.GetMessageByInitRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>int64 user_con_index = 2;</code>
     */
    long getUserConIndex();
}
