// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf enum {@code im.MessageType}
 */
public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MessageType_Not_Use = 0;</code>
     */
    MessageType_Not_Use(0),
    /**
     * <code>Text = 1;</code>
     */
    Text(1),
    /**
     * <code>Image = 2;</code>
     */
    Image(2),
    /**
     * <code>Video = 3;</code>
     */
    Video(3),
    /**
     * <code>Forward = 4;</code>
     */
    Forward(4),
    /**
     * <code>Cmd = 1000;</code>
     */
    Cmd(1000),
    /**
     * <code>SpecialCmd = 1001;</code>
     */
    SpecialCmd(1001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MessageType_Not_Use = 0;</code>
     */
    public static final int MessageType_Not_Use_VALUE = 0;
    /**
     * <code>Text = 1;</code>
     */
    public static final int Text_VALUE = 1;
    /**
     * <code>Image = 2;</code>
     */
    public static final int Image_VALUE = 2;
    /**
     * <code>Video = 3;</code>
     */
    public static final int Video_VALUE = 3;
    /**
     * <code>Forward = 4;</code>
     */
    public static final int Forward_VALUE = 4;
    /**
     * <code>Cmd = 1000;</code>
     */
    public static final int Cmd_VALUE = 1000;
    /**
     * <code>SpecialCmd = 1001;</code>
     */
    public static final int SpecialCmd_VALUE = 1001;


    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
        return forNumber(value);
    }

    public static MessageType forNumber(int value) {
        switch (value) {
            case 0:
                return MessageType_Not_Use;
            case 1:
                return Text;
            case 2:
                return Image;
            case 3:
                return Video;
            case 4:
                return Forward;
            case 1000:
                return Cmd;
            case 1001:
                return SpecialCmd;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
                public MessageType findValueByNumber(int number) {
                    return MessageType.forNumber(number);
                }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
        return violet.gateway.common.proto_gen.im.Im.getDescriptor().getEnumTypes().get(1);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.MessageType)
}

