// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

public interface MessageSendRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:im.MessageSendRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 con_short_id = 1;</code>
     */
    long getConShortId();

    /**
     * <code>string con_id = 2;</code>
     */
    java.lang.String getConId();

    /**
     * <code>string con_id = 2;</code>
     */
    com.google.protobuf.ByteString
    getConIdBytes();

    /**
     * <code>int32 con_type = 3;</code>
     */
    int getConType();

    /**
     * <code>int64 client_msg_id = 4;</code>
     */
    long getClientMsgId();

    /**
     * <code>int32 msg_type = 5;</code>
     */
    int getMsgType();

    /**
     * <code>string msg_content = 6;</code>
     */
    java.lang.String getMsgContent();

    /**
     * <code>string msg_content = 6;</code>
     */
    com.google.protobuf.ByteString
    getMsgContentBytes();
}
