// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.gateway.common.proto_gen.im;

/**
 * Protobuf type {@code im.SendMessageRequest}
 */
public final class SendMessageRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:im.SendMessageRequest)
        SendMessageRequestOrBuilder {
    // Use SendMessageRequest.newBuilder() to construct.
    private SendMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SendMessageRequest() {
        userId_ = 0L;
        conShortId_ = 0L;
        conId_ = "";
        conType_ = 0;
        clientMsgId_ = 0L;
        msgType_ = 0;
        msgContent_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private SendMessageRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        userId_ = input.readInt64();
                        break;
                    }
                    case 16: {

                        conShortId_ = input.readInt64();
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        conId_ = s;
                        break;
                    }
                    case 32: {

                        conType_ = input.readInt32();
                        break;
                    }
                    case 40: {

                        clientMsgId_ = input.readInt64();
                        break;
                    }
                    case 48: {

                        msgType_ = input.readInt32();
                        break;
                    }
                    case 58: {
                        java.lang.String s = input.readStringRequireUtf8();

                        msgContent_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return violet.gateway.common.proto_gen.im.Im.internal_static_im_SendMessageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return violet.gateway.common.proto_gen.im.Im.internal_static_im_SendMessageRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        violet.gateway.common.proto_gen.im.SendMessageRequest.class, violet.gateway.common.proto_gen.im.SendMessageRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;

    /**
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
        return userId_;
    }

    public static final int CON_SHORT_ID_FIELD_NUMBER = 2;
    private long conShortId_;

    /**
     * <code>int64 con_short_id = 2;</code>
     */
    public long getConShortId() {
        return conShortId_;
    }

    public static final int CON_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object conId_;

    /**
     * <code>string con_id = 3;</code>
     */
    public java.lang.String getConId() {
        java.lang.Object ref = conId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            conId_ = s;
            return s;
        }
    }

    /**
     * <code>string con_id = 3;</code>
     */
    public com.google.protobuf.ByteString
    getConIdBytes() {
        java.lang.Object ref = conId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            conId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CON_TYPE_FIELD_NUMBER = 4;
    private int conType_;

    /**
     * <code>int32 con_type = 4;</code>
     */
    public int getConType() {
        return conType_;
    }

    public static final int CLIENT_MSG_ID_FIELD_NUMBER = 5;
    private long clientMsgId_;

    /**
     * <code>int64 client_msg_id = 5;</code>
     */
    public long getClientMsgId() {
        return clientMsgId_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 6;
    private int msgType_;

    /**
     * <code>int32 msg_type = 6;</code>
     */
    public int getMsgType() {
        return msgType_;
    }

    public static final int MSG_CONTENT_FIELD_NUMBER = 7;
    private volatile java.lang.Object msgContent_;

    /**
     * <code>string msg_content = 7;</code>
     */
    public java.lang.String getMsgContent() {
        java.lang.Object ref = msgContent_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msgContent_ = s;
            return s;
        }
    }

    /**
     * <code>string msg_content = 7;</code>
     */
    public com.google.protobuf.ByteString
    getMsgContentBytes() {
        java.lang.Object ref = msgContent_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            msgContent_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (userId_ != 0L) {
            output.writeInt64(1, userId_);
        }
        if (conShortId_ != 0L) {
            output.writeInt64(2, conShortId_);
        }
        if (!getConIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, conId_);
        }
        if (conType_ != 0) {
            output.writeInt32(4, conType_);
        }
        if (clientMsgId_ != 0L) {
            output.writeInt64(5, clientMsgId_);
        }
        if (msgType_ != 0) {
            output.writeInt32(6, msgType_);
        }
        if (!getMsgContentBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgContent_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (userId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, userId_);
        }
        if (conShortId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(2, conShortId_);
        }
        if (!getConIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, conId_);
        }
        if (conType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, conType_);
        }
        if (clientMsgId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(5, clientMsgId_);
        }
        if (msgType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(6, msgType_);
        }
        if (!getMsgContentBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgContent_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof violet.gateway.common.proto_gen.im.SendMessageRequest)) {
            return super.equals(obj);
        }
        violet.gateway.common.proto_gen.im.SendMessageRequest other = (violet.gateway.common.proto_gen.im.SendMessageRequest) obj;

        boolean result = true;
        result = result && (getUserId()
                == other.getUserId());
        result = result && (getConShortId()
                == other.getConShortId());
        result = result && getConId()
                .equals(other.getConId());
        result = result && (getConType()
                == other.getConType());
        result = result && (getClientMsgId()
                == other.getClientMsgId());
        result = result && (getMsgType()
                == other.getMsgType());
        result = result && getMsgContent()
                .equals(other.getMsgContent());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getUserId());
        hash = (37 * hash) + CON_SHORT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getConShortId());
        hash = (37 * hash) + CON_ID_FIELD_NUMBER;
        hash = (53 * hash) + getConId().hashCode();
        hash = (37 * hash) + CON_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getConType();
        hash = (37 * hash) + CLIENT_MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getClientMsgId());
        hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgType();
        hash = (37 * hash) + MSG_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getMsgContent().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(violet.gateway.common.proto_gen.im.SendMessageRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code im.SendMessageRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:im.SendMessageRequest)
            violet.gateway.common.proto_gen.im.SendMessageRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_SendMessageRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_SendMessageRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            violet.gateway.common.proto_gen.im.SendMessageRequest.class, violet.gateway.common.proto_gen.im.SendMessageRequest.Builder.class);
        }

        // Construct using violet.gateway.common.proto_gen.im.SendMessageRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            userId_ = 0L;

            conShortId_ = 0L;

            conId_ = "";

            conType_ = 0;

            clientMsgId_ = 0L;

            msgType_ = 0;

            msgContent_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return violet.gateway.common.proto_gen.im.Im.internal_static_im_SendMessageRequest_descriptor;
        }

        public violet.gateway.common.proto_gen.im.SendMessageRequest getDefaultInstanceForType() {
            return violet.gateway.common.proto_gen.im.SendMessageRequest.getDefaultInstance();
        }

        public violet.gateway.common.proto_gen.im.SendMessageRequest build() {
            violet.gateway.common.proto_gen.im.SendMessageRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public violet.gateway.common.proto_gen.im.SendMessageRequest buildPartial() {
            violet.gateway.common.proto_gen.im.SendMessageRequest result = new violet.gateway.common.proto_gen.im.SendMessageRequest(this);
            result.userId_ = userId_;
            result.conShortId_ = conShortId_;
            result.conId_ = conId_;
            result.conType_ = conType_;
            result.clientMsgId_ = clientMsgId_;
            result.msgType_ = msgType_;
            result.msgContent_ = msgContent_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof violet.gateway.common.proto_gen.im.SendMessageRequest) {
                return mergeFrom((violet.gateway.common.proto_gen.im.SendMessageRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(violet.gateway.common.proto_gen.im.SendMessageRequest other) {
            if (other == violet.gateway.common.proto_gen.im.SendMessageRequest.getDefaultInstance()) return this;
            if (other.getUserId() != 0L) {
                setUserId(other.getUserId());
            }
            if (other.getConShortId() != 0L) {
                setConShortId(other.getConShortId());
            }
            if (!other.getConId().isEmpty()) {
                conId_ = other.conId_;
                onChanged();
            }
            if (other.getConType() != 0) {
                setConType(other.getConType());
            }
            if (other.getClientMsgId() != 0L) {
                setClientMsgId(other.getClientMsgId());
            }
            if (other.getMsgType() != 0) {
                setMsgType(other.getMsgType());
            }
            if (!other.getMsgContent().isEmpty()) {
                msgContent_ = other.msgContent_;
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            violet.gateway.common.proto_gen.im.SendMessageRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (violet.gateway.common.proto_gen.im.SendMessageRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private long userId_;

        /**
         * <code>int64 user_id = 1;</code>
         */
        public long getUserId() {
            return userId_;
        }

        /**
         * <code>int64 user_id = 1;</code>
         */
        public Builder setUserId(long value) {

            userId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 user_id = 1;</code>
         */
        public Builder clearUserId() {

            userId_ = 0L;
            onChanged();
            return this;
        }

        private long conShortId_;

        /**
         * <code>int64 con_short_id = 2;</code>
         */
        public long getConShortId() {
            return conShortId_;
        }

        /**
         * <code>int64 con_short_id = 2;</code>
         */
        public Builder setConShortId(long value) {

            conShortId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 con_short_id = 2;</code>
         */
        public Builder clearConShortId() {

            conShortId_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object conId_ = "";

        /**
         * <code>string con_id = 3;</code>
         */
        public java.lang.String getConId() {
            java.lang.Object ref = conId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                conId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string con_id = 3;</code>
         */
        public com.google.protobuf.ByteString
        getConIdBytes() {
            java.lang.Object ref = conId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                conId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string con_id = 3;</code>
         */
        public Builder setConId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            conId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string con_id = 3;</code>
         */
        public Builder clearConId() {

            conId_ = getDefaultInstance().getConId();
            onChanged();
            return this;
        }

        /**
         * <code>string con_id = 3;</code>
         */
        public Builder setConIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            conId_ = value;
            onChanged();
            return this;
        }

        private int conType_;

        /**
         * <code>int32 con_type = 4;</code>
         */
        public int getConType() {
            return conType_;
        }

        /**
         * <code>int32 con_type = 4;</code>
         */
        public Builder setConType(int value) {

            conType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 con_type = 4;</code>
         */
        public Builder clearConType() {

            conType_ = 0;
            onChanged();
            return this;
        }

        private long clientMsgId_;

        /**
         * <code>int64 client_msg_id = 5;</code>
         */
        public long getClientMsgId() {
            return clientMsgId_;
        }

        /**
         * <code>int64 client_msg_id = 5;</code>
         */
        public Builder setClientMsgId(long value) {

            clientMsgId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 client_msg_id = 5;</code>
         */
        public Builder clearClientMsgId() {

            clientMsgId_ = 0L;
            onChanged();
            return this;
        }

        private int msgType_;

        /**
         * <code>int32 msg_type = 6;</code>
         */
        public int getMsgType() {
            return msgType_;
        }

        /**
         * <code>int32 msg_type = 6;</code>
         */
        public Builder setMsgType(int value) {

            msgType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 msg_type = 6;</code>
         */
        public Builder clearMsgType() {

            msgType_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object msgContent_ = "";

        /**
         * <code>string msg_content = 7;</code>
         */
        public java.lang.String getMsgContent() {
            java.lang.Object ref = msgContent_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msgContent_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string msg_content = 7;</code>
         */
        public com.google.protobuf.ByteString
        getMsgContentBytes() {
            java.lang.Object ref = msgContent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msgContent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string msg_content = 7;</code>
         */
        public Builder setMsgContent(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msgContent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string msg_content = 7;</code>
         */
        public Builder clearMsgContent() {

            msgContent_ = getDefaultInstance().getMsgContent();
            onChanged();
            return this;
        }

        /**
         * <code>string msg_content = 7;</code>
         */
        public Builder setMsgContentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msgContent_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:im.SendMessageRequest)
    }

    // @@protoc_insertion_point(class_scope:im.SendMessageRequest)
    private static final violet.gateway.common.proto_gen.im.SendMessageRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new violet.gateway.common.proto_gen.im.SendMessageRequest();
    }

    public static violet.gateway.common.proto_gen.im.SendMessageRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMessageRequest>
            PARSER = new com.google.protobuf.AbstractParser<SendMessageRequest>() {
        public SendMessageRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new SendMessageRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<SendMessageRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMessageRequest> getParserForType() {
        return PARSER;
    }

    public violet.gateway.common.proto_gen.im.SendMessageRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

