// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/http.proto

package violet.gateway.common.proto_gen.http;

public interface FollowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:http.FollowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 to_user_id = 1;</code>
   */
  long getToUserId();

  /**
   * <code>int32 follow_type = 2;</code>
   */
  int getFollowType();
}
