// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/http.proto

package violet.gateway.common.proto_gen.http;

public interface GetMessageByConversationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:http.GetMessageByConversationRequest)
    com.google.protobuf.MessageOrBuilder {
}
